### ISSUE TITLE
There was an issue while attempting to enable Xbox Live

### ISSUE THREAD

**Issue by naaturaz** [Microsoft/xbox-live-unity-plugin#103]
Hi

I can't enable the app with the Association Wizard.

![wizard issue](https://user-images.githubusercontent.com/8929243/29240552-b3f2ff84-7f35-11e7-80fb-58977663271d.png)

App Info:
Package/Identity/Name | 9023AatlantisStudios.Koteekoo
-- | --
Package/Identity/Publisher | CN=3EB4758E-A8A4-4A65-B26A-8D1B61D4AD7A

Thanks

**Comment by veleek** [comment]
Hey @naaturaz,

We've found the issue that's preventing you from enabling using the Association Wizard and we'll work to get it fixed pretty soon.  In the meantime, you should be able to enable your product by heading over to DevCenter and going through the enable flow there.

After that's completed you should be able to re-run the Association Wizard and it will pull down and setup the required configuration that you need.

**Comment by Daggy117** [comment]
I am having the same issue. Where and how do I enable the product outside of the association wizard? I've been looking all over my dashboard at developer.windows.com and I am not sure where I do this.

**Comment by jasonsandlin** [comment]
We have resolved an issue that was blocking the enable flow. Please try enabling and then associating again now

**Comment by jasonsandlin** [comment]
The original bug should be fixed now as well.  Be sure to update to https://github.com/Microsoft/xbox-live-unity-plugin/releases/tag/v1707qfe2 or later for the fix.
