### ISSUE TITLE
Latest Unity File From Releases Missing Scripts??

### ISSUE THREAD

**Issue by DutyStudios** [Microsoft/xbox-live-unity-plugin#104]
Hello, it seems like the unity package you all have for release is missing scripts. None of the scripts inside of unity after importing it has a way to update stats to xbox live or leaderboards. Looking at some of the scripts here in the git repository, it seems like one of the main ones is statmanager, which is missing after you import to Unity. Also the documentation for updating stats for leaderboards isn't really detailed here or here https://docs.microsoft.com/en-us/windows/uwp/xbox-live/get-started-with-creators/add-stats-and-leaderboards-in-unity. Or did I miss something somewhere? Thank you so much for all the hard work you all have put in thus far though.

**Comment by jasonsandlin** [comment]
I think we discussed this in https://github.com/Microsoft/xbox-live-unity-plugin/issues/105 

If there's more, let me know and I'll reopen

**Comment by DutyStudios** [comment]
Actually @jasonsandlin, I played around with it last night and I feel like I got it all setup correctly,  however when I run it on my PC through visual studio, nothing shows up in the leaderboard. Is that because I'm in a test environment? Should my score at least show up in there? How can I make sure it is actually working properly. Or do I have to run it on my dev Xbox One?

**Comment by jasonsandlin** [comment]
You don't have to dev on Xbox One.  It'll work on PC too, and it'll work in a test environment.  The easiest way to debug is to send over a Fiddler trace so we can see what network calls are going out.  Here's how to set that up: https://docs.microsoft.com/en-us/windows/uwp/xbox-live/using-xbox-live/troubleshooting/how-to-set-up-fiddler-for-debugging.  Just send over a .saz file and we'll take a look

**Comment by DutyStudios** [comment]
Ok, thank you. I will send one over as soon as I get a chance.

**Comment by DutyStudios** [comment]
Quick question, what kind of data should I be seeing inside of it? I did put one other account as a test user as well.

**Comment by jasonsandlin** [comment]
Well, you should see a call to statswrite.xboxlive.com with the stats data you set, and then you should see a leaderboard call with the leaderboard data coming back down and the leaderboard should be for the stat you sent up and have previously configured on the windows dev center portal website in the xbox live section.

**Comment by jasonsandlin** [comment]
Another thing you might want to do is run:
https://github.com/Microsoft/xbox-live-samples/tree/master/Samples/CreatorsSDK/Leaderboards/UWP/Cpp

This sample does the stats write & leaderboard read.  Run fiddler while its running and you'll see the calls you should see in your game.

**Comment by DutyStudios** [comment]
That's some great info. What should I see in the leaderboard? In the Unity editor it logs in the fake user and leaderboard shows all 10 fake users with scores... however on Visual Studio test, it logs me in with my gamerscore name and number, no picture, but the leaderboard is completely blank. Should I at least be seeing the other account that's a test user?

**Comment by DutyStudios** [comment]
Ok great. I'm not sure what time I'll be home to mess with it tonight but this is great info on where I can look and test in case you all are away tomorrow and thi a weekend. I'll update the post with any findings and send in a .saz file asap.

**Comment by jasonsandlin** [comment]
Yeah in the editor, fake data is expected.  But when you build via Visual Studio its real data and you should see your own leaderboard.  You should see data for all users who have posted data to that stat assuming you've configured the stat to be a leaderboard at https://developer.microsoft.com/en-US/dashboard

**Comment by DutyStudios** [comment]
I do have a stat setup there and I'm using the same ID on my IntegerStat. I'll send you that .raz file as soon as I can. Probably not much else you can do without it. Thanks a lot for all the input this far though.

**Comment by jasonsandlin** [comment]
Yeah, we can narrow down what the issue is anyway once we see that

**Comment by jasonsandlin** [comment]
Let me know when you have this info and we'll reopen and investigate

**Comment by DutyStudios** [comment]
Hey @jasonsandlin , sorry for not getting back with you sooner. I ran the game on my xbox and it actually posted a score. Not sure what the problem was but it seems to be working now.
