### ISSUE TITLE
Build errors after adding Unity package

### ISSUE THREAD

**Issue by BionicPony** [Microsoft/xbox-live-unity-plugin#105]
After adding the Unity package I receive the following two errors when trying to build:

UnityEditor.BuildPlayerWindow+BuildMethodException: Build failed with errors.
  at UnityEditor.BuildPlayerWindow+DefaultBuildMethods.BuildPlayer (BuildPlayerOptions options) [0x001b9] in C:\buildslave\unity\build\Editor\Mono\BuildPlayerWindowBuildMethods.cs:162 
  at UnityEditor.BuildPlayerWindow.CallBuildMethods (Boolean askForBuildLocation, BuildOptions defaultBuildOptions) [0x00050] in C:\buildslave\unity\build\Editor\Mono\BuildPlayerWindowBuildMethods.cs:83 

and

UnityException: Failed to run reference rewriter with command --target="Temp\StagingArea\Assembly-CSharp.dll" --additionalreferences="Temp\StagingArea","C:\Program Files (x86)\Windows Kits\10\UnionMetadata\10.0.15063.0\Facade","C:\Program Files (x86)\Windows Kits\10\References\10.0.15063.0\Windows.ApplicationModel.Calls.CallsVoipContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.15063.0\Windows.ApplicationModel.SocialInfo.SocialInfoContract\2.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.15063.0\Windows.Devices.DevicesLowLevelContract\3.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.15063.0\Windows.Devices.Printers.PrintersContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.15063.0\Windows.Foundation.FoundationContract\3.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.15063.0\Windows.Foundation.UniversalApiContract\4.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.15063.0\Windows.Graphics.Printing3D.Printing3DContract\3.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.15063.0\Windows.Networking.Connectivity.WwanContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.15063.0\Windows.Services.Store.StoreContract\2.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.15063.0\Windows.Services.TargetedContent.TargetedContentContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.15063.0\Windows.System.Profile.ProfileHardwareTokenContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.15063.0\Windows.System.Profile.ProfileSharedModeContract\2.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.15063.0\Windows.UI.ViewManagement.ViewManagementViewScalingContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.15063.0\Windows.ApplicationModel.Activation.ActivatedEventsContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.15063.0\Windows.ApplicationModel.Activation.ActivationCameraSettingsContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.15063.0\Windows.ApplicationModel.Activation.ContactActivatedEventsContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.15063.0\Windows.ApplicationModel.Activation.WebUISearchActivatedEventsContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.15063.0\Windows.ApplicationModel.Background.BackgroundAlarmApplicationContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.15063.0\Windows.ApplicationModel.Calls.Background.CallsBackgroundContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.15063.0\Windows.ApplicationModel.Calls.LockScreenCallContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.15063.0\Windows.ApplicationModel.FullTrustAppContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.15063.0\Windows.ApplicationModel.Preview.InkWorkspace.PreviewInkWorkspaceContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.15063.0\Windows.ApplicationModel.Preview.Notes.PreviewNotesContract\2.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.15063.0\Windows.ApplicationModel.Resources.Management.ResourceIndexerContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.15063.0\Windows.ApplicationModel.Search.Core.SearchCoreContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.15063.0\Windows.ApplicationModel.Search.SearchContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.15063.0\Windows.ApplicationModel.StartupTaskContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.15063.0\Windows.ApplicationModel.Wallet.WalletContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.15063.0\Windows.Devices.Custom.CustomDeviceContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.15063.0\Windows.Devices.Portable.PortableDeviceContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.15063.0\Windows.Devices.Printers.Extensions.ExtensionsContract\2.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.15063.0\Windows.Devices.Scanners.ScannerDeviceContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.15063.0\Windows.Devices.Sms.LegacySmsApiContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.15063.0\Windows.Gaming.Input.GamingInputPreviewContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.15063.0\Windows.Gaming.Preview.GamesEnumerationContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.15063.0\Windows.Gaming.UI.GameChatOverlayContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.15063.0\Windows.Globalization.GlobalizationJapanesePhoneticAnalyzerContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.15063.0\Windows.Management.Deployment.Preview.DeploymentPreviewContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.15063.0\Windows.Management.Workplace.WorkplaceSettingsContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.15063.0\Windows.Media.Capture.AppBroadcastContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.15063.0\Windows.Media.Capture.AppCaptureContract\4.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.15063.0\Windows.Media.Capture.CameraCaptureUIContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.15063.0\Windows.Media.Capture.GameBarContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.15063.0\Windows.Media.Devices.CallControlContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.15063.0\Windows.Media.MediaControlContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.15063.0\Windows.Media.Playlists.PlaylistsContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.15063.0\Windows.Media.Protection.ProtectionRenewalContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.15063.0\Windows.Networking.NetworkOperators.LegacyNetworkOperatorsContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.15063.0\Windows.Networking.Sockets.ControlChannelTriggerContract\2.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.15063.0\Windows.Perception.Automation.Core.PerceptionAutomationCoreContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.15063.0\Windows.Security.EnterpriseData.EnterpriseDataContract\4.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.15063.0\Windows.Security.ExchangeActiveSyncProvisioning.EasContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.15063.0\Windows.Services.Maps.GuidanceContract\2.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.15063.0\Windows.Services.Maps.LocalSearchContract\3.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.15063.0\Windows.System.Profile.SystemManufacturers.SystemManufacturersContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.15063.0\Windows.System.Profile.ProfileRetailInfoContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.15063.0\Windows.System.UserProfile.UserProfileContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.15063.0\Windows.System.UserProfile.UserProfileLockScreenContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.15063.0\Windows.UI.ApplicationSettings.ApplicationsSettingsContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.15063.0\Windows.UI.Core.AnimationMetrics.AnimationMetricsContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.15063.0\Windows.UI.Core.CoreWindowDialogsContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.15063.0\Windows.UI.Xaml.Hosting.HostingContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.15063.0\Windows.Web.Http.Diagnostics.HttpDiagnosticsContract\2.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.15063.0\Windows.System.SystemManagementContract\3.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.15063.0\Windows.ApplicationModel.Calls.CallsPhoneContract\3.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.15063.0\Windows.ApplicationModel.CommunicationBlocking.CommunicationBlockingContract\2.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.15063.0\Windows.Devices.SmartCards.SmartCardBackgroundTriggerContract\3.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.15063.0\Windows.Devices.SmartCards.SmartCardEmulatorContract\4.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.15063.0\Windows.Embedded.DeviceLockdown.DeviceLockdownContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.15063.0\Windows.Networking.NetworkOperators.NetworkOperatorsFdnContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.15063.0\Windows.Phone.PhoneContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.15063.0\Windows.Phone.StartScreen.DualSimTileContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\10.0.15063.0\Windows.UI.WebUI.Core.WebUICommandBarContract\1.0.0.0" --platform="C:\Program Files (x86)\Windows Kits\10\UnionMetadata\10.0.15063.0\Facade\Windows.winmd" --dbg=pdb --support="Temp\StagingArea\WinRTLegacy.dll" --supportpartialns=Unity.Partial --system=System --lock=UWP\project.lock.json --alt=System.Xml.Serialization;System.Collections,System.Collections.NonGeneric;System.Reflection,System.Reflection.TypeExtensions;System.IO,System.IO.FileSystem;System.Net,System.Net.Primitives;System.Net.Sockets,System.Net.Primitives;System.Xml,System.Xml.XmlDocument;<winmd>,Windows.winmd;<winmd>,Windows.ApplicationModel.Calls.CallsVoipContract.winmd;<winmd>,Windows.ApplicationModel.SocialInfo.SocialInfoContract.winmd;<winmd>,Windows.Devices.DevicesLowLevelContract.winmd;<winmd>,Windows.Devices.Printers.PrintersContract.winmd;<winmd>,Windows.Foundation.FoundationContract.winmd;<winmd>,Windows.Foundation.UniversalApiContract.winmd;<winmd>,Windows.Graphics.Printing3D.Printing3DContract.winmd;<winmd>,Windows.Networking.Connectivity.WwanContract.winmd;<winmd>,Windows.Services.Store.StoreContract.winmd;<winmd>,Windows.Services.TargetedContent.TargetedContentContract.winmd;<winmd>,Windows.System.Profile.ProfileHardwareTokenContract.winmd;<winmd>,Windows.System.Profile.ProfileSharedModeContract.winmd;<winmd>,Windows.UI.ViewManagement.ViewManagementViewScalingContract.winmd;<winmd>,Windows.ApplicationModel.Activation.ActivatedEventsContract.winmd;<winmd>,Windows.ApplicationModel.Activation.ActivationCameraSettingsContract.winmd;<winmd>,Windows.ApplicationModel.Activation.ContactActivatedEventsContract.winmd;<winmd>,Windows.ApplicationModel.Activation.WebUISearchActivatedEventsContract.winmd;<winmd>,Windows.ApplicationModel.Background.BackgroundAlarmApplicationContract.winmd;<winmd>,Windows.ApplicationModel.Calls.Background.CallsBackgroundContract.winmd;<winmd>,Windows.ApplicationModel.Calls.LockScreenCallContract.winmd;<winmd>,Windows.ApplicationModel.FullTrustAppContract.winmd;<winmd>,Windows.ApplicationModel.Preview.InkWorkspace.PreviewInkWorkspaceContract.winmd;<winmd>,Windows.ApplicationModel.Preview.Notes.PreviewNotesContract.winmd;<winmd>,Windows.ApplicationModel.Resources.Management.ResourceIndexerContract.winmd;<winmd>,Windows.ApplicationModel.Search.Core.SearchCoreContract.winmd;<winmd>,Windows.ApplicationModel.Search.SearchContract.winmd;<winmd>,Windows.ApplicationModel.StartupTaskContract.winmd;<winmd>,Windows.ApplicationModel.Wallet.WalletContract.winmd;<winmd>,Windows.Devices.Custom.CustomDeviceContract.winmd;<winmd>,Windows.Devices.Portable.PortableDeviceContract.winmd;<winmd>,Windows.Devices.Printers.Extensions.ExtensionsContract.winmd;<winmd>,Windows.Devices.Scanners.ScannerDeviceContract.winmd;<winmd>,Windows.Devices.Sms.LegacySmsApiContract.winmd;<winmd>,Windows.Gaming.Input.GamingInputPreviewContract.winmd;<winmd>,Windows.Gaming.Preview.GamesEnumerationContract.winmd;<winmd>,Windows.Gaming.UI.GameChatOverlayContract.winmd;<winmd>,Windows.Globalization.GlobalizationJapanesePhoneticAnalyzerContract.winmd;<winmd>,Windows.Management.Deployment.Preview.DeploymentPreviewContract.winmd;<winmd>,Windows.Management.Workplace.WorkplaceSettingsContract.winmd;<winmd>,Windows.Media.Capture.AppBroadcastContract.winmd;<winmd>,Windows.Media.Capture.AppCaptureContract.winmd;<winmd>,Windows.Media.Capture.CameraCaptureUIContract.winmd;<winmd>,Windows.Media.Capture.GameBarContract.winmd;<winmd>,Windows.Media.Devices.CallControlContract.winmd;<winmd>,Windows.Media.MediaControlContract.winmd;<winmd>,Windows.Media.Playlists.PlaylistsContract.winmd;<winmd>,Windows.Media.Protection.ProtectionRenewalContract.winmd;<winmd>,Windows.Networking.NetworkOperators.LegacyNetworkOperatorsContract.winmd;<winmd>,Windows.Networking.Sockets.ControlChannelTriggerContract.winmd;<winmd>,Windows.Perception.Automation.Core.PerceptionAutomationCoreContract.winmd;<winmd>,Windows.Security.EnterpriseData.EnterpriseDataContract.winmd;<winmd>,Windows.Security.ExchangeActiveSyncProvisioning.EasContract.winmd;<winmd>,Windows.Services.Maps.GuidanceContract.winmd;<winmd>,Windows.Services.Maps.LocalSearchContract.winmd;<winmd>,Windows.System.Profile.SystemManufacturers.SystemManufacturersContract.winmd;<winmd>,Windows.System.Profile.ProfileRetailInfoContract.winmd;<winmd>,Windows.System.UserProfile.UserProfileContract.winmd;<winmd>,Windows.System.UserProfile.UserProfileLockScreenContract.winmd;<winmd>,Windows.UI.ApplicationSettings.ApplicationsSettingsContract.winmd;<winmd>,Windows.UI.Core.AnimationMetrics.AnimationMetricsContract.winmd;<winmd>,Windows.UI.Core.CoreWindowDialogsContract.winmd;<winmd>,Windows.UI.Xaml.Hosting.HostingContract.winmd;<winmd>,Windows.Web.Http.Diagnostics.HttpDiagnosticsContract.winmd;<winmd>,Windows.System.SystemManagementContract.winmd;<winmd>,Windows.ApplicationModel.Calls.CallsPhoneContract.winmd;<winmd>,Windows.ApplicationModel.CommunicationBlocking.CommunicationBlockingContract.winmd;<winmd>,Windows.Devices.SmartCards.SmartCardBackgroundTriggerContract.winmd;<winmd>,Windows.Devices.SmartCards.SmartCardEmulatorContract.winmd;<winmd>,Windows.Embedded.DeviceLockdown.DeviceLockdownContract.winmd;<winmd>,Windows.Networking.NetworkOperators.NetworkOperatorsFdnContract.winmd;<winmd>,Windows.Phone.PhoneContract.winmd;<winmd>,Windows.Phone.StartScreen.DualSimTileContract.winmd;<winmd>,Windows.UI.WebUI.Core.WebUICommandBarContract.winmd --ignore=System.IConvertible,mscorlib.
Error: type `Microsoft.Xbox.Services.Leaderboard.LeaderboardResult` doesn't exist in target framework. It is referenced from Assembly-CSharp.dll at Leaderboard.
Error: type `Microsoft.Xbox.Services.XboxLiveUser` doesn't exist in target framework. It is referenced from Assembly-CSharp.dll at System.Void Leaderboard::Start().
Error: type `Microsoft.Xbox.Services.XboxLiveUser` doesn't exist in target framework. It is referenced from Assembly-CSharp.dll at System.Void Leaderboard::Start().
Error: type `Microsoft.Xbox.Services.XboxLiveUser` doesn't exist in target framework. It is referenced from Assembly-CSharp.dll at System.Void Leaderboard::Start().
Catastrophic failure while running rrw: Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'Microsoft.Xbox.Services.UWP.CSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
   at Unity.SearchPathAssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
   at Unity.NuGetAssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
   at Unity.SearchPathAssemblyResolver.Resolve(AssemblyNameReference name)
   at Mono.Cecil.MetadataResolver.Resolve(TypeReference type) in C:\buildslave\cecil\build\Mono.Cecil\MetadataResolver.cs:line 106
   at Mono.Cecil.MetadataResolver.Resolve(MethodReference method) in C:\buildslave\cecil\build\Mono.Cecil\MetadataResolver.cs:line 216
   at Mono.Cecil.MethodReference.Resolve() in C:\buildslave\cecil\build\Mono.Cecil\MethodReference.cs:line 170
   at Unity.ReferenceRewriter.RewriteTyp<message truncated>

Any ideas where I should start looking for a solution?

**Comment by DutyStudios** [comment]
Hmmm... What version if Unity are you using? And are you using the settings for Windows 10 UWP?

**Comment by BionicPony** [comment]
Unity version = 2017.1.0p2
Build target is Universal Windows Platform.

If we import the Xbox UnityPackage into a blank project it will build.  If we import it into our finished game it causes a bunch of errors.  We solved several sets of errors already, but this one has us really stuck.  I don't think rebuilding the game from scratch into a new project is a viable solution, but that's the only thing we can think of at this point.  These newest error messages themselves read like gibberish to us.

**Comment by DutyStudios** [comment]
How did you guys get the package in there? Did you just download that latest release version and then import it? Or did you do all of the PowerShell stuff?

**Comment by BionicPony** [comment]
We didn't do all the powershell stuff.  We just downloaded the latest version and imported it.

**Comment by DutyStudios** [comment]
Yeah same here. Maybe some other package is conflicting with it? Have you tried removing any others or do you have any others in the project? Sorry I'm little help, I don't have much experience yet.

**Comment by DutyStudios** [comment]
Maybe you need to update your Windows kit? https://developer.microsoft.com/en-us/windows/downloads/windows-10-sdk

**Comment by DutyStudios** [comment]
Did you end up figuring out what it was?

**Comment by BionicPony** [comment]
No, we haven't figured it out.  I don't think we're going to be able to either.  When we added the Xbox Live Unity Package to our finished game it caused us to get over 60 errors when we tried to build.  We managed to track down and fix the sources of almost all of them, but these last two read like gibberish.  They provide us with no information we can use to figure out what the problem is.

At this point we only have two options that I can see.  We can create a new project from scratch, add in the Xbox Live Unity Package and slowly build our game again around it stopping to build the project periodically.  We probably won't get the same errors, but if we do, we can narrow down the cause to be a compatibility issue with whatever changes we made since the last test build.

The other option is to hope Microsoft puts out a new version of the package that happens to fix the problem(s) with the current one, and/or provides documentation that addresses them.

We're still working on it, but since there isn't much we can try we'll probably give up and rebuild our otherwise finished game from scratch around this one problematic package.

**Comment by jasonsandlin** [comment]
We'd be happy to fix it or take a pull request that fixes the issue, but we need to know how to reproduce the issue first.  All the projects we've seen so far build correctly, so we'll need to figure out what's causing this errors to fix them or document how to avoid

**Comment by BionicPony** [comment]
I can submit information on the errors I managed to fix so far if that helps you with documenting them to help other users.  Where could we submit that?  In this thread?

As far as this set of errors go, I don't think I'll be able to help.  If I find something while rebuilding the game in a new project I'll post it here.  In the meantime, do the error messages I posted in the original message make any sense to you?  If so maybe they can help point me towards an area to look into.  If they're as meaningless to you as they are to me then I'll start rebuilding the game from scratch shortly.

**Comment by jasonsandlin** [comment]
If you are changing code in the plugin, the best is to click the "Fork" button in the upper right of https://github.com/Microsoft/xbox-live-unity-plugin/ and clone into that and update that code and push it.  Then we can look at your changes.

Those errors don't mean much to me so not sure what causes them

**Comment by DutyStudios** [comment]
Do you think the Windows SDK might have something to do with it? I would try downloading Visual Studio 2017 and especially the latest Windows SDK if you haven't already.

**Comment by DutyStudios** [comment]
From yours C:\Program Files (x86)\Windows Kits\10\References\10.0.15063.0, I don't have the folder 10.0.15063.0 in my path.

**Comment by BionicPony** [comment]
I've never changed any code in the plugin.  The errors so far we're compatibility errors.  For example, one set of errors, I believe they were of the "The type or namespace name `SyntaxTree' could not be found. Are you missing an assembly reference?" nature were fixed by by going into Unity > Preferences > External Tools > and switching from using MonoDevelop to Visual Studio.  It makes sense that this would be missed in documentation.  Anyone testing the package on Microsoft's end probably uses Visual Studio automatically and wouldn't even think about using MonoDevelop, whereas a lot of Unity Developer's use MonoDevelop by default.

The second set of errors we found, I believe were of the "the type or namespace "Xbox" does not exist in the namespace "Microsoft". " variety.  We tried several things to fix that one and I planned on recreating it and finding the exact step that fixed it before posting.  From memory, I think the solution might have been simply to close out Unity after adding the package, then when reopening it Unity automatically reconfigured some scripts and the error went away.  Then again I'm going from memory so that may be wrong.

**Comment by BionicPony** [comment]
Thanks DutyStudios, but that can't be the problem.  We're successfully able to build games using the package on our dev machine, just not the one we want.  The problem logically cannot be with our Visual Studio Installation as that is used by the other projects we've tested successfully.

**Comment by DutyStudios** [comment]
Not having the newer Windows SDK could be causing it though since this is a newer package. Idk, would be worth a try imo instead of starting over from scratch,

**Comment by jasonsandlin** [comment]
Ah yeah, the SyntaxTree errors will happen if you don't use Visual Studio or the Visual Studio Tools for Unity installed -- which is doc'd as required here https://github.com/Microsoft/xbox-live-unity-plugin

Let us know if you spot the cause of the other errors

**Comment by BionicPony** [comment]
I must have missed that part of the documentation.  If I find definitive answers to the other problems I'll update.

**Comment by DutyStudios** [comment]
Hey Jasonandlin, could you point me in the direction of stat updates with the released package? I put in an issue on it.

**Comment by jasonsandlin** [comment]
"stat updates"?  What do you mean?

**Comment by DutyStudios** [comment]
I don't see any documentation or functions for pushing the stats to the leaderboards.

**Comment by jasonsandlin** [comment]
Ah.  You can open one of the example scenes to see some pre-built examples:
https://github.com/Microsoft/xbox-live-unity-plugin/tree/master/Assets/Xbox%20Live/Examples
The leaderboard or updatestat scene will show you how this is done.  

There's also a doc page here:
https://docs.microsoft.com/en-us/windows/uwp/xbox-live/get-started-with-creators/add-stats-and-leaderboards-in-unity

**Comment by DutyStudios** [comment]
I don't see what function to call to push them to the leaderboard though. Like for example android and unity there is a line like so Games.Leaderboards.submitScore(mGoogleApiClient, LEADERBOARD_ID, 1337);

**Comment by DutyStudios** [comment]
I don't see anything like that in that documentation or looking through the scripts that are in the latest release package I downloaded and imported.

**Comment by jasonsandlin** [comment]
Ah.  "Leaderboards are based off of player stats that are sent to the Xbox Live service by the game. Therefore, leaderboard data is read only, as you cannot modify them directly."  

Basically this means you don't submit to leaderboards.  You set stats and that's it.  Then in your Xbox Live config portal page, you configure from which stats you want to create a leaderboard from.

**Comment by BionicPony** [comment]
I'm not trying to nitpick, but I just read through the documentation you linked to and it doesn't say anything about setting your External Tools in Unity to Visual Studio. It only mentions that you need to download Visual Studio, which would make perfect sense since you need Visual Studio after you build your project in Unity.  I don't think it's obvious that you would need to use Visual Studio as your script editor while in Unity.  Some quick googling found at least one other person stuck at the same spot so it isn't just me that didn't see the connection.  I think explicitly adding that step to documentation at some point would be helpful.  

Again, I'm not trying to nitpick.  This program is in it's early stages and I'm legitimately trying to help others avoid problems.

**Comment by DutyStudios** [comment]
Ok, so are they basically always auto updated?

**Comment by jasonsandlin** [comment]
Agreed @BionicPony, we'll get this added.  btw, feel free to edit the docs if that's easiest for you.  One of the cool things about docs.microsoft.com is that its backed by github so you just click on the edit button in the corner and you can make changes to the docs in your browser and submit a pull request.

**Comment by jasonsandlin** [comment]
@DutyStudios yeah when stats are set they will flow up to the service automatically every 5 mins or when you call RequestFlushToService (which you should call when something important happens like ending a match, zone, etc).  RequestFlushToService will only send up once every 30 seconds.

**Comment by DutyStudios** [comment]
Ah, thank you so much @jasonsandlin. I will try that later on!

**Comment by jasonsandlin** [comment]
@BionicPony, I submitted a doc pull request at https://github.com/MicrosoftDocs/windows-uwp/pull/183/files
