### ISSUE TITLE
VisualStudio 2017 Bug - D3D -  Master Mode - NavMesh Bug

### ISSUE THREAD

**Issue by naaturaz** [Microsoft/xbox-live-unity-plugin#109]
While using Unity: 2017.1.0f3
and VisualStudio: 15.3.0 

The navmesh works perfectly in Debug and Release mode. 
Now if I set it to Master mode the NavMesh system doesn't work as intended.
The NavMesh agents are dismissing dynamically created obstacles.

Note I'm has been able to Deploy to the XBOX with Release and Debug mode. I'm using Master mode only to get rid of the 'Development Build' text

Also when I'm exporting to the UWP I'm using D3D option. 
I'm using D3D options because I wanted to get rid of the big white square around the screen and pointer

Also, I'm changing the project.lock.json file to work. Otherwise, I get an error and doesn't compile:
Changed from UAP,Version=v10.0.xxxxxx to UAP,Version=v10.0
{
  "version": 3,
  "targets": {
    "UAP,Version=v10.0": {
https://forum.unity3d.com/threads/unable-to-build-even-an-empty-project.488278/#post-3184871

VS info:
Microsoft Visual Studio Community 2017 
Version 15.3.0
VisualStudio.15.Release/15.3.0+26730.3
Microsoft .NET Framework
Version 4.7.02046

Installed Version: Community

Visual Basic 2017   00369-60000-00001-AA585
Microsoft Visual Basic 2017

Visual C# 2017   00369-60000-00001-AA585
Microsoft Visual C# 2017

Application Insights Tools for Visual Studio Package   8.8.00712.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2017   15.0.30726.0
ASP.NET and Web Tools 2017

ASP.NET Core Razor Language Services   1.0
Provides languages services for ASP.NET Core Razor.

ASP.NET Template Engine 2017   15.0.30726.0
ASP.NET Template Engine 2017

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

JavaScript UWP Project System   2.0
JavaScript UWP Project System

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

NuGet Package Manager   4.3.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

TypeScript   2.3.4.0
TypeScript tools for Visual Studio

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for Unity   3.3.0.0
Visual Studio Tools for Unity

Visual Studio Tools for Universal Windows Apps   15.0.26730.00
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

Unity export settings:

![unity export set](https://user-images.githubusercontent.com/8929243/29476541-856f8f0e-8432-11e7-8845-117e88dcc508.png)

I'm not clicking on the Unity C# Projects because was giving me another error.

Thanks in advance

**Comment by jasonsandlin** [comment]
I don't know - I recommend you follow up with Unity support or on Unity's forums
