### ISSUE TITLE
Association wizard crashes as soon as I try to enable XBOX live

### ISSUE THREAD

**Issue by mstvir** [Microsoft/xbox-live-unity-plugin#112]
Association wizard crashes as soon as I try to enable XBOX Live on my application. No particular error is shown just good old crash. 
![screen shot 08-22-17 at 09 44 am](https://user-images.githubusercontent.com/2890148/29550388-876013a8-871e-11e7-9b49-d9240ed12fb3.PNG)
Thus I decided to enable XBOX Live services from Windows Dashboard, oddly enough I can't find the settings in Dashboard too...
![screen shot 08-22-17 at 09 48 am](https://user-images.githubusercontent.com/2890148/29550497-232e83e6-871f-11e7-98bd-19171ccbde43.PNG)

**Comment by veleek** [comment]
Can you provide the AppId for your application so that we can see if we can find out what's causing the problem?

**Comment by mstvir** [comment]
Of course
Package/Identity/Name : 32396myBit.XBOXLiveTest
Package/Identity/Publisher: CN=9FC17D2B-1507-462C-83DF-17E76829E0BD

**Comment by SwarmHammer** [comment]
have you made sure to select the Games category when starting your title submission? the XBox Live service will only show up if a title is set up as a Game.

**Comment by mstvir** [comment]
@SwarmHammer, I changed right after I posted this issue, but still had no luck with enabling services. 
As you suggested this morning I tried to reserve another app name, however dev center gave me error, that something is wrong with my browser session. 
I switched to Microsoft Edge, tried again, and it worked. 
Really, I can believe that browser was causing that issue.
However, Association Wizard was able to associate app only after I manually enabled XBOX live services.

Thanks everyone for help.

**Comment by SwarmHammer** [comment]
Well the good reason here is that any microsoft website will work best with microsoft browser. What I was actually suggesting is not to delete the reserved app from dev center, only the submission sub-category of the app you want to activate xbox live. Glad you had sort it out. My tests was with an old app that had the same problem in Chrome (highly possible that clearing chrome cache might have also worked)
