### ISSUE TITLE
Player stats are not stored in Xbox Live

### ISSUE THREAD

**Issue by davidpol** [Microsoft/xbox-live-unity-plugin#117]
Hello,

We have successfully integrated the plugin into our project and have the sign-in working fine, but we are now facing an issue with the player stats/leaderboards. In our case, we only have a high-score leaderboard. We set the value of the appropriate integer stat at the end of the game, but it looks like the stat is never actually stored in Xbox Live. Trying to retrieve the value of the stat on a subsequent launch of the game always returns 0. Also, the leaderboard returns nothing when playing from a build (it  returns fake data when playing from the editor, though).

The way we are retrieving/setting the value of the stat is by means of the IntegerStat prefab, which is filled with the appropriate dashboard data. Then, at runtime, we simply do
    
    var prevScore = stat.Value;

in order to retrieve the value of the stat and

    stat.Value = newScore;

in order to update it.

I have several questions related to this:

- Is there more to player stats/leaderboards or are we missing something?

- Do we need to worry about explicitly calling StatsManagerComponent.RequestFlushToService or is that taken care of by the plugin? Even calling it right after changing the stat does not seem to make a difference.

- When testing from the editor, should the fake data be modified in any way? What I mean is, if I am logged in as "Fake User 1" and change the value of a stat, should that be reflected in the fake values returned by the leaderboard or is the data always the same? Because in our case it definitely is always the same.

- Do we need to worry about not sending the value of the stat if it is not higher than the current one or is that taken care of by the plugin?

Thank you in advance!

**Comment by davidpol** [comment]
Just wanted to add that we did some further testing with the Leaderboard and UpdateStat example scenes (changing the ID of the stat prefabs to that of our stat) and the result is the same. The Leaderboard scene always returns an empty list and the UpdateStat shows the stat being updated on a given launch, but subsequent launches always return 0, as if the stat never got to Xbox Live.

**Comment by jasonsandlin** [comment]
1) You don't need to do anything but it only uploads every 5 minutes.  If you want to it to upload the stats you've set then you need to called RequestToFlush which you should call at important events (changing scene, level, etc).  RequestToFlush also has a rate limit and it'll only send data to the service every 30 seconds, but you can call it as often as you want but it may not do anything if its been less than 30 seconds.  

Try either waiting or calling request and you should see data getting the service.  Fiddler is a good tool to monitor what's going to the service if you want to see the traffic.  https://docs.microsoft.com/en-us/windows/uwp/xbox-live/using-xbox-live/troubleshooting/how-to-set-up-fiddler-for-debugging

2) 
When testing from the editor, the data is fake and it doesn't emulate reading.  It just returns the same fake data always.

3)
As for "setting the value to higher or not", just set it to whatever you want the stat to be.  There's no logic in the plugin or the service beyond the simple replace.  You set it to what you want the stat value to be.

**Comment by davidpol** [comment]
Thank you for the information, Jason!

It turns out the stat is being sent just fine for the team member who is testing on an actual Xbox (I am testing on PC). It looks like I can log into Xbox Live and see the leaderboard, but the stat is never sent for me. I will do some further digging with Fiddler but, as we are exclusively aiming for Xbox, it is just out of curiosity at this point.

**Comment by nyarsulik** [comment]
Sorry for dropping this question on a closed issue, but I can't seem to find the correct method for calling RequestToFlush.  My game passed the "Test" button and I believe I am setting my values correctly (the same way they are listed at the top of the post, literally just setting the integer value equal to the new high value) but even if I let my game run for over 5 minutes on Xbox I can't seem to get the leaderboard to update with anything, it just sits blank.  I'm not doing any manual flush calls, so I think that may be what I am missing.

I found this code:
StatsManagerComponent.RequestFlushToService(XboxLiveUserManager.Instance.GetSingleModeUser().User, true);

But, now I am getting the warning:
error CS0120: An object reference is required to access non-static member

Is there a simpler "flush all" that doesn't need any extra references setup?

Thanks!
Nick

**Comment by jasonsandlin** [comment]
Here's an example call: 

https://github.com/Microsoft/xbox-live-unity-plugin/blob/master/Assets/Xbox%20Live/Scripts/Leaderboard.cs#L110

**Comment by nyarsulik** [comment]
This was perfect, thank you!  Adding in that extra Flush call (plus some additional code that was in the Start function at that link) was what I needed to get them to finally show up on the console.  Thanks!
