### ISSUE TITLE
XboxSocialUser.DisplayPicRaw returning invalid URL

### ISSUE THREAD

**Issue by mikeoliphant** [Microsoft/xbox-live-unity-plugin#121]
I'm not sure that this is an issue with the plugin, because I think it was working last week, but the gamer pic url in DisplayPicRaw field of XboxSocialUser is currently not working properly.

This issue seems to be that the Url includes an "&mode=Padding" parameter. If this parameter is removed, the Url works correctly.

**Comment by MSFT-Heba** [comment]
Thanks for reporting this, mikeoliphant.  We'll work on a fix for this and update you here once the fix is out.

**Comment by mikeoliphant** [comment]
This field is now just coming back null. I opened a new issue for it:

https://github.com/Microsoft/xbox-live-unity-plugin/issues/144

**Comment by ilookha** [comment]
The mode=Padding issue is still there, the server responds with a status of 400 (Bad Request) if "&mode=Padding" isn't removed manually.

**Comment by jplafonta** [comment]
We believe this was a service side issue that should now be resolved.  If you are still seeing this problem, please reactivate the issue.
