### ISSUE TITLE
Can't build the plugin

### ISSUE THREAD

**Issue by demonixis** [Microsoft/xbox-live-unity-plugin#122]
Hello,

I try to build the plugin from source to remove `Unity.Compat.dll` and `Unity.Tasks.dll` dependencies, to be able to use the plugin with .Net 4.6. The first step to do that is to compile the sources without any modifications. So I read the README.md and do the following things

1. Clone the repository with submodules
2. Install the Xbox Live extensions
3. Run the Setup.ps1 script

That's the result

![image](https://user-images.githubusercontent.com/1017126/30101245-df14d24a-92eb-11e7-9d6a-c1a0d8283812.png)

I use Visual Studio 2017, that's what is installed

![image](https://user-images.githubusercontent.com/1017126/30101368-5ace0fe6-92ec-11e7-9cb6-aa313de3902a.png)

Any idea? Have you plans to support .Net 4.6 now it's shipped in Unity 2017.1?

Thanks for you help.

Edit: I was able to build the C++ and C# libs by changing the VS target (v141) in the C++ solution.

**Comment by jasonsandlin** [comment]
You should be able to use VS2017, but you need to install the v140 tools in the VS2017 installer under the individual components tab.

**Comment by demonixis** [comment]
Great thank you, I'll give it another try tomorrow!
