### ISSUE TITLE
Exception whilst trying to open the Profile Picker

### ISSUE THREAD

**Issue by coxlin** [Microsoft/xbox-live-unity-plugin#123]
Hi there.

I am getting an exception:
**_AggregateException_ctor_DefaultMessage: Access is denied. (Excep_FromHResult 0x80070005)_**

When trying to open the profile picker. This is the same when I try to log in using the UserProfile prefab. 
I have tried this on a couple of accounts now, any suggestions?

**Comment by ayrik** [comment]
I'm getting the same thing using this code:
```cs
Debug.Log("Enable Winmd Support");
if(xboxUser == null || xboxUser.WindowsSystemUser == null)
{
	bool done = false;
	var autoPicker = new Windows.System.UserPicker { AllowGuestAccounts = true };
	autoPicker.PickSingleUserAsync().AsTask().ContinueWith(
			task =>
			{
				if(task.Exception != null)
					Debug.LogError("Exception occured: " + task.Exception.Message);
				else if(task.Status == TaskStatus.RanToCompletion)
				{
					WindowsSystemUser = task.Result;
					done = true;
				}
			});

	while(!done) yield return null;
}

xboxUser = new XboxLiveUser(WindowsSystemUser);
```

**Comment by MSFT-Heba** [comment]
Hi coxlin and ayrik, 
Are you testing this on Xbox or PC? 
Also did you make sure to add the required multiple users tag in package.manifest.xml after exporting to UWP as highlighted at: [https://docs.microsoft.com/en-us/windows/uwp/xbox-live/get-started-with-creators/add-multi-user-support](https://docs.microsoft.com/en-us/windows/uwp/xbox-live/get-started-with-creators/add-multi-user-support)?

That error usually is a result of missing that part.

**Comment by coxlin** [comment]
This was on Xbox for me, I will try that and let you know. Ther error seemed to be occurring even with one user so it may be worth updating the docs  if this is the fix

**Comment by coxlin** [comment]
OK, adding that solved the first exception, however, I am getting a new Arg_NullReferenceException after sign in. 

`private void DoSignIn()
    {
#if ENABLE_WINMD_SUPPORT
         var autoPicker = new Windows.System.UserPicker { AllowGuestAccounts = true };
            autoPicker.PickSingleUserAsync().AsTask().ContinueWith(
                    task =>
                        {
                            if (task.Status == TaskStatus.RanToCompletion)
                            {
                                this.XboxLiveUser.WindowsSystemUser = task.Result;
                                this.XboxLiveUser.Initialize();
                                StartCoroutine(SignInCoroutine());
                            }
                            else
                            {
                                var sb = new System.Text.StringBuilder();
                                sb.AppendLine(task.Status.ToString());
                                sb.AppendLine(task.Exception.HResult.ToString());
                                sb.AppendLine(task.Exception.Message);
                                sb.AppendLine(task.Exception.InnerException.Message);
                                throw new Exception(sb.ToString());
                            }
                        });
#endif
    }`

Heare is a snippet of the exception details:

System.NullReferenceException occurred
  HResult=0x80004003
  Message=Arg_NullReferenceException
  Source=<unknown>
  StackTrace:
   ...
System.Threading.Tasks.ContinuationTaskFromResultTask`1.InnerInvoke() in f:\dd\ndp\fxcore\CoreRT\src\System.Private.Threading\src\System\Threading\Tasks\TaskContinuation.cs:line 159
   at System.Threading.Tasks.Task.Execute() in f:\dd\ndp\fxcore\CoreRT\src\System.Private.Threading\src\System\Threading\Tasks\Task.cs:line 2299

**Comment by coxlin** [comment]
Ok, after fixing some dropped references, upgrading Unity, upgrading the nuget packages etc I hit another exception 

System.Exception occurred
  HResult=0x80131500
  Message=Method 'XboxLiveUser..ctor(User)' was not included in compilation, but was referenced in XboxLiveUserInfo.InitializeWithWindowsSystemUser(). There may have been a missing assembly.
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>

**Comment by MSFT-Heba** [comment]
Hi coxlin,
What is the backend you're using for the project? .NET (2.0) or IL2CPP (and .NET 4.6)?

**Comment by jplafonta** [comment]
I was not able to repro this with the latest release.  If you are still seeing the issue with release 1711, please reactivate this issue.
