### ISSUE TITLE
Null Reference exception when starting SignInAndProfile.unity scene on a CLEAN machine

### ISSUE THREAD

**Issue by DDReaper** [Microsoft/xbox-live-unity-plugin#125]
This has taken me a long time to diagnose.  But now I've fixed it, I cannot replicate it on the same machine.
(Unity 2017.2b10 & VS 15.3)

Taking the approach of a brand new developer taking up XBL, with a clean machine that had not logged into a sandpit already, I went through the standard steps:

1: Create app on dashboard
2: Register it with XBL
3: Setup test account
4: Create new Unity game
5: Install XBL Unity package (1707 QFE 3)
6: Associate game with Sandpit and switch PC to use sandpit
7: Set UWP player settings to use .NET & .NET 4.6
8: Build Unity game using SignInAndProfile example (no changes)
9: Open built project and Run

This would consistently cause a Null Reference exception, stopping in the Task completion for signin.

Eventually, I deleted the 1707 release and used the 1704 asset, this WORKED.
Upgrading to 1707 or starting with a new solution with 1707 still works and signs in the Test User automatically.  As if some step is cached or skipped because it has previously been logged on.

So, I don't know if it's a fault in the autologon, if waiting until the project is fully started before logging on (as click to logon in 1704 worked?) or some timing or whatever.

Just searching for some way to "Log off" the single user to try and replicate again.

**Comment by DDReaper** [comment]
Ok, eventually managed to signout using the GameBar and logging off the Xbox App. (Still cannot find an API call to Logoff?? so I can switch users)
The Sign-out Event is NOT captured but when I closed and started the app again using 1707, the app starts crashing again

---
System.AggregateException occurred
  HResult=0x80131500
  Message=One or more errors occurred. (Object reference not set to an instance of an object.)
  Source=Assembly-CSharp
  StackTrace:
   at TaskYieldInstruction.get_keepWaiting() in E:\Development\Unity\Sandbox\UWPLiveTest2\Assets\Xbox Live\Scripts\UnityTaskExtensions.cs:line 65
   at UnityEngine.SetupCoroutine.InvokeMoveNext(IEnumerator enumerator, IntPtr returnValueAddress)
   at UnityEngine.SetupCoroutine.$Invoke1InvokeMoveNext(Int64 instance, Int64* args)
   at UnityEngine.Internal.$MethodUtility.InvokeMethod(Int64 instance, Int64* args, IntPtr method)

Inner Exception 1:
NullReferenceException: Object reference not set to an instance of an object.
---

The profile picker does not appear and no selection of a profile is possible

**Comment by tecraveiro** [comment]
I think Silent Sign In is not working as intended in 1707 QFE 3, if you comment out the SignInSilentlyAsync() and use the SignInAsync() in UserProfile instead it should work.

Are you setting Compilation Overrides to Use Net Core in the Player Settings so ENABLE_WINMD_SUPPORT catches?

**Comment by DDReaper** [comment]
Not enabled ENABLE_WINMD_SUPPORT but I'll give it a try if you believe that will help.  Thanks for the update

**Comment by tecraveiro** [comment]
Do not explicitly set it in the params, IL2CPP does already enable it and it is enabled for .NET if you select "Use Net Core" in compile override. You need the ENABLE_WINMD_SUPPORT path for the Windows user to be logged into Xbox Live.

**Comment by MSFT-Heba** [comment]
DDReaper,
are you using IL2CPP for the backend? Could you try switching to .Net for the backend and .NET 2.0 for the compatibility level?

**Comment by DDReaper** [comment]
@tecraveiro 's comment fixed it
> I think Silent Sign In is not working as intended in 1707 QFE 3, if you comment out the SignInSilentlyAsync() and use the SignInAsync() in UserProfile instead it should work.

It does indeed seem like the "SignInSilentlyAsync" function is indeed broken. Switching it back to the SignInAsync function fixes it.  I suspect this needs fixing.

Just had to whip up some XBL code for one developer, so I'll do another fresh project tomorrow and try an IL2CPP build to see if the SignInSilentlyAsync function works there or not.

**Comment by MSFT-Heba** [comment]
We are looking into the SignInSilentlyAsync issue and will update you once the fix is out.

**Comment by DDReaper** [comment]
Fantastic. Doing a post for DBP on XBL integration, so will mention that (or leave it out if the fix is up before I hit post :D)

**Comment by jasonsandlin** [comment]
What's DBP?

**Comment by DDReaper** [comment]
#ShockHorror
Dream Build Play - http://dreambuildplay.com/
I've done several posts so far already here (and on my blog) https://devpost.com/software/dreambuildplayresources

Next one was going to be on XBL integration.  All part of the MS MVP service :D

**Comment by jasonsandlin** [comment]
Ah cool.

**Comment by tecraveiro** [comment]
@MSFT-Heba @DDReaper: 

> DDReaper,
> are you using IL2CPP for the backend? Could you try switching to .Net for the backend and .NET 2.0 for the compatibility level?

This fixed silent sign-in for me. That and "Use Net Core" in Compile Override for WinRT. Any way to tell when it is better to use .NET 2.0 and 4.6?

**Comment by DDReaper** [comment]
Yup, confirmed. Removing the SignInSiliently call does fix the issue. Trouble is, the QFE release is broken until it's fixed / sorted.
