### ISSUE TITLE
XboxLiveUser SignInSilentlyAsync and SignInAsync sometimes never return

### ISSUE THREAD

**Issue by mikeoliphant** [Microsoft/xbox-live-unity-plugin#129]
I am seeing circumstance where SignInSilentlyAsync and SignInAsync are failing to return. So far it seems to only happen on my Xbox One in developer mode. It also seems to be related to having an account that has not yet agreed to the terms of services pop-up, but it does not always happen.

When the problem occurs, SignInSilentlyAsync will never return a result. Calling SignInAsync pops up the black overlay with a progress circle and the screen never goes away.

**Comment by MSFT-Heba** [comment]
Hi @mikeoliphant, are you by any chance using IL2CPP and .NET 4.6? Could you try switching to .NET backend and .NET 2.0?

**Comment by mikeoliphant** [comment]
I am using .NET with .NET 2.0 subset.

**Comment by MSFT-Heba** [comment]
We'll continue trying to repro then. If there is anything more you can provide us to help repro this, that would be much appreciated. For example, are you using the UserProfile script? Anything special about your setup?

Another thing that might help would be if you could share a Fiddler trace of when this situation happens. Do you think that's possible?

**Comment by mikeoliphant** [comment]
I am not using the UserProfile script, but the code in question is really simple:

```
XboxLiveUser user = new XboxLiveUser();

SignInResult result = await user.SignInSilentlyAsync();
```

In the case when the problem occurs, the await never completes.

I'll look into Fiddler.

**Comment by ayrik** [comment]
If you're using `await` then you are using .NET 4.6 experimental. What happens if you switch back to .NET 3.5 stable like suggested above?

**Comment by mikeoliphant** [comment]
My Xbox Live code is in a separately compiled UWP assembly that uses Microsoft.Xbox.Services.UWP.CSharp directly - I don't think I can use 3.5 there.

In the Unity build, though, I am using .Net 2.0 Subset.

**Comment by rygaar72** [comment]
I am using .NET and the .NET2.0 subset, and have seen issues with logging in, where it just never returns and my game gets stuck on the login page.  Not good for users, and has already earned me a bad review.

I need to investigate further, but it seems to occur if the internet bandwidth is maxed out, e.g. something is downloading, chewing up all the available bandwidth.  

Just tonight one of my kids had the issue, and I got them to sign out of the xbox and try and sign in again, but they got an Xbox error saying there is a problem and they cannot be signed in right now.  I then discovered something was downloading and stopped it.  They could then sign into the xbox AND into the game.

So, is it possible that the plugin isn't handling errors in a very robust way, and can get it in a state where it fails during login and never returns?  

I will try some more tests tomorrow to try and reproduce the problem by maxing out the bandwidth while trying to start the game and sign in.

Thoughts?

**Comment by wilderic** [comment]
I have reviews stating the same thing. I've switched to the multiple user profile picker for now in hopes that it works better.

**Comment by rygaar72** [comment]
I've been doing some more testing, and things don't go too well when you don't have an internet connection, or you lose it.  

I have put some code to detect a hung login, and if it encounters one, start the game in an offline mode.  Then at least people can play it if they don't have a network, or something goes horribly wrong.

I'm interested to know how the dev's think the plugin should behave if network connections are lost etc.

Is it built to work using Xbox Live in an offline state?  Is that possible, or do you need a network connection for plugin to work reliably?

If possible, I think it needs to be able to work online / offline reliably.  Of course you wont be able to query leaderboards if offline, but would be nice to make this easily detectable so we can tell the user.

**Comment by jasonsandlin** [comment]
Agree, it should work online / offline reliably.  We will address these issues before next release

**Comment by jplafonta** [comment]
Please try the 2018.2 preview; we believe the issue should be fixed there.  If you are still having this problem after updating, please reactivate this issue.
