### ISSUE TITLE
Leaderboard stops working if you try to go into a scene twice that has it.

### ISSUE THREAD

**Issue by DutyStudios** [Microsoft/xbox-live-unity-plugin#130]
Downloaded latest release and I'm still having a problem with this.

This is what the error says:
MissingReferenceException: The object of type 'RectTransform' has been destroyed but you are still trying to access it.
Your script should either check if it is null or you should not destroy the object.
Leaderboard.LoadResult (Microsoft.Xbox.Services.Leaderboard.LeaderboardResult result) (at Assets/Xbox Live/Scripts/Leaderboard.cs:275)
Leaderboard.GetLeaderboardCompleted (System.Object sender, XboxLivePrefab.StatEventArgs e) (at Assets/Xbox Live/Scripts/Leaderboard.cs:246)
StatsManagerComponent.OnGetLeaderboardCompleted (XboxLivePrefab.StatEventArgs statEvent) (at Assets/Xbox Live/Scripts/Stats/StatsManagerComponent.cs:92)
StatsManagerComponent.Update () (at Assets/Xbox Live/Scripts/Stats/StatsManagerComponent.cs:60)

**Comment by ayubhassan** [comment]
I think you need like a "DontDestroyOnLoad" to make sure it doesn't get destroyed when switching between scenes or loading the same scene.

**Comment by MSFT-Heba** [comment]
@DutyStudios: Could you share a bit about your setup? Are you using the Leaderboard prefab as-is? Do you have it setup differently?

**Comment by DutyStudios** [comment]
I have one that I've made some changes to but I've also tried it with the
default leaderboards to make sure it wasn't my leaderboard.

**Comment by ayubhassan** [comment]
The problem is the “ObjectPool” script is getting destroyed.

**Comment by DutyStudios** [comment]
Ok thanks, I'll look into that tonight.

**Comment by DutyStudios** [comment]
Hey @ayubhassan, I ended up making the leaderboard inactive and making it DontDestroy and it is working. I don't know if this is ideal but it works. Thanks!

**Comment by jasonsandlin** [comment]
Still sounds like a bug we should fix.  I'm going to keep this open till we do

**Comment by rakhad** [comment]
@DutyStudios

I can't reproduce this bug using the latest release (1707 QFE 4). My repro steps are 
1. Load into the Leaderboard scene
2. Navigate to an empty scene
3. Navigate back to the Leaderboard scene

Are you still hitting this bug? If so, what steps are you taking to repro it?
