### ISSUE TITLE
Can't pass certification, how do I contact the certification team?

### ISSUE THREAD

**Issue by BionicPony** [Microsoft/xbox-live-unity-plugin#135]
I released a game last month that was built using Unity.  It uses the Unity Package to enable User Profile so users have the option of signing-in.  The problem is the certification team keeps failing it for the following reason.  If a user selects "NO" when initially prompted enable the permission to allow sign-in, the game allows them to continue playing.  Someone on the certification team believes this to be in violation of the following:

****************************************************************
App Policies: 10.13.5 Xbox Live Active User and Gamertag
Notes To Developer
Because your game uses Xbox Live, it must:
 · Create at least one active user and sign the user into Xbox. 
 · Display the user’s Xbox gamertag as the primary display and profile name.
Please add this behavior and resubmit your game.

Steps to Reproduce: 
1. Launch the app.
2. Select "No" for Xbox Live permission request to cancel sign-in.
3. Notice that the gameplay should be blocked until signing the user into Xbox Live services. However, your app is still playable by cancelling Xbox Live login.
 *****************************************************************

This is odd since the game uses absolutely no Xbox Live Services whatsoever.  I only even enabled sign-in because I was emailed and informed that this had to be added to all Xbox Creator's Program games.  

I then downloaded every free game on the Creator's Program marketplace to see how others implemented this feature.  It turns out that every single game I checked implemented this exactly the way I did.  You can decline the permission in any game on the store and keep playing.  

Can I modify the Unity Package's Prefabs so that a user declining this permission gets kicked to a screen where the only option is to try again?  Probably.  I haven't looked through it to see what callbacks are available.  Before I do that I would like to find out conclusively if this is an actual requirement and not just one person on the cert team who doesn't understand what they're doing (that I happen to keep getting).  If this IS a requirement, then it might be a good idea to modify the Unity Package and/or instructions to make it compliant with this rule.  Given that my past experiences with the certification team (while developing for windows and windows phone) have been nothing short of pure nightmares, I am forced to assume this is probably an error on their end.

That brings me to my initial questions.  Is there any way to actually contact them?  I've tried submitting Certification Report Feedback, but I never get a response.

**Comment by jasonsandlin** [comment]
We will forward to the right folks

**Comment by jasonsandlin** [comment]
You should be hearing from them.
