### ISSUE TITLE
Featured Stat Short Timespan update variable type?

### ISSUE THREAD

**Issue by DutyStudios** [Microsoft/xbox-live-unity-plugin#136]
Does anyone know what the Stat needs to be for time leaderboards? I'm assuming it needs to be double but it would be nice if it was documented somewhere, like how google actually says-- 

Time leaderboards present scores in hours / minutes / seconds / hundredths of a second format. You must submit scores as milliseconds, so 66032 would be interpreted as 1:06.03.

Is it the same for these?

**Comment by XboxLiveForum** [comment]
They can store TimeSpan as an integer number. If it is hero stats, they can mark the Display Format as one of the timespan format.

These are the definitions in xdp regarding to Display Format:

SHORT TIME SPAN: Unlimited number of hours, with minutes, seconds and milliseconds precision. Requires Display Unit to be specified as well. For example: "34:17:36.789" 

LONG TIME SPAN: Unlimited number of days, with hours and minutes precision. Requires Display Unit to be specified as well. For example: "1d 10h 17m"
