### ISSUE TITLE
UserProfile and OnApplicationQuit()

### ISSUE THREAD

**Issue by rygaar72** [Microsoft/xbox-live-unity-plugin#137]
In the UserProfile class:
`    private void OnApplicationQuit()
    {
        XboxLive.Instance.PresenceWriter.StopWriter();
    }`

Looking at the unity documentation [https://docs.unity3d.com/ScriptReference/MonoBehaviour.OnApplicationQuit.html](url)
, it looks like this is not called for Windows Store Apps:

> Note: On Windows Store Apps and Windows Phone 8.1 there's no application quit event, consider using OnApplicationFocus event when focusStatus equals false.

Does this apply for the Xbox deployed UWP apps?

If so, is it a problem this code is never called?

thanks

**Comment by jasonsandlin** [comment]
Its no a problem, but it is unneeded code if its never called.  I'll mark this a bug to fix in a future release.

**Comment by jplafonta** [comment]
This is fixed in 1711 release.
