### ISSUE TITLE
Leaderboard prefab issue

### ISSUE THREAD

**Issue by prgrmr25** [Microsoft/xbox-live-unity-plugin#140]
The leaderboard prefab doesn’t show gamer’s picture, it just shows an orange image.

**Comment by DutyStudios** [comment]
It's hit or miss on mine. It actually loads it more often when I run it on an actual Xbox.

**Comment by jasonsandlin** [comment]
Thanks.  We will add this feature in an upcoming release

**Comment by jplafonta** [comment]
This is fixed in the 1711 release. If you are still seeing the issue after upgrading, please reactivate this issue.

**Comment by ayubhassan** [comment]
I still have the same problem after upgrading!

**Comment by rakhad** [comment]
Are you still experiencing this issue? If so, can you share the steps to reproduce it.

The gamer pics show up for me when I download the 1711 unity package and configure the Xbox Live\Examples\Leaderboard scene.

**Comment by prgrmr25** [comment]
1802 fixed this! tnx
