### ISSUE TITLE
DisplayPicRaw field of XboxSocialUser is null

### ISSUE THREAD

**Issue by mikeoliphant** [Microsoft/xbox-live-unity-plugin#144]
The DisplayPicRaw field of XboxSocialUser has just recently started coming back null.

After getting creating a social user group using CreateSocialUserGroupFromList and then getting an XboxSocialUser from the group with GetUser, the DisplayPicRaw is null.

This seems to have stopped working at the same time as the fix for a previous issue went live:

https://github.com/Microsoft/xbox-live-unity-plugin/issues/142

**Comment by TTSSoftware** [comment]
What I'm seeing with this is that none of the social user fields are populated from the CreateSocialUserGroupFromList method, including Gamerscore, Gamertag, DisplayName, PreferredColor, DisplayPicRaw, etc, so it's not limited to just DisplayPicRaw.  I know all of those were working before the recent Xbox Live back end changes.

**Comment by MSFT-Heba** [comment]
@TTSSoftware  and @mikeoliphant  This issue should now be resolved. Could you please confirm on your sides as well?

**Comment by TTSSoftware** [comment]
Yes, it seems to be working correctly now.  Thank you.

**Comment by MSFT-Heba** [comment]
Great to hear. We're going to be closing this issue now. Please do let us know if you're still seeing this.
