### ISSUE TITLE
TypeLoadException GameSaveProvider

### ISSUE THREAD

**Issue by SebastianCmentowski** [Microsoft/xbox-live-unity-plugin#145]
I am trying to set up a Unity-title for XLC. Apart from the known issue regarding ILC2PP I am now facing a TypeLoadException when deploying to Mobile while using Connected Storage:

_TypeLoadException: Requested Windows Runtime type 'Windows.Gaming.XboxLive.Storage.GameSaveProvider' is not registered._

Unfortunatly, Unity keeps being buggy when debugging UWP-builds, thus I cannot give a full stack trace. However the exception appears during initialization of the GameSaveHelper (GameSaveProvider.GetForUserAsync) and only appears on the mobile platform - PC works fine.

**Comment by MSFT-Heba** [comment]
Hi Sebastian,
Connected Storage is currently only supported on the PC and console. Mobile is not supported.

**Comment by SebastianCmentowski** [comment]
Ohhh - if that's the case I am sorry for the misunderstanding. I never read this anywhere (but probably missed it in my hurry). Of course this is quite unfortunate as it opposes the "universality" idea of UWP (and to my knowledge there isn't an easy way to distinguish mobile and other platforms in Unity without building it manually for each platform). Anyways, thanks for clarification.
