### ISSUE TITLE
Stats / leaderboards stopped working in RETAIL

### ISSUE THREAD

**Issue by rygaar72** [Microsoft/xbox-live-unity-plugin#146]
A few days ago I noticed that retrieval and persistence of stats stopped working for my title in RETAIL!?!  This morning Leaderboards are no longer returning either.  I haven’t submitted a new build to the store for a while, so no changes on my side.

I’m using Unity 2017.1.1f1.  Unity plugin, 1707 QFE 3 Release.  Slight mods to the the unity code side of the plugin to integrate with my game better, nothing major.

Not sure if it’s related, but I am also having issues with certification, getting failures because they can’t log in.  I can log in just fine in RETAIL.  Different users and different xboxes all work fine.  The version that is failing cert now has been in the store for a while, and it is the version I am running without issue from here, so I’m not sure what’s going on.

I have been in contact with Stacey Haffner and she has suggested I raise this issue here and get fiddler traces, which I hope to do tonight.

Has anything changed server side lately which might explain this?

Thanks

**Comment by MSFT-Heba** [comment]
Hi @rygaar72 
We were able to repro the stats issue and believe we have a fix that should be released soon. Will keep this thread updated.

**Comment by MSFT-Heba** [comment]
To clarify, the fix will be on the service side, so there'll be no code changes needed.

**Comment by rygaar72** [comment]
Thanks for the info on the stats issue Heba.

Regarding the login issue, I have just worked out it is ONLY occurring for new users of the game, existing users are fine.  Probably something I have done on my side, so I will investigate that issue now and hopefully address.  If I continue to have problems I will raise a separate issue for it.

cheers

**Comment by rygaar72** [comment]
Also, when do you think the stats fix will be in?

**Comment by rygaar72** [comment]
Looks to be fixed now.
