### ISSUE TITLE
LoadProfileInfo doesn't wait until WWW coroutine is complete

### ISSUE THREAD

**Issue by ilookha** [Microsoft/xbox-live-unity-plugin#147]
Hi, LoadProfileInfo does only "yield return null" before checking the status of the WWW result. One frame wouldn't be enough to end the request and so the gamerpic sprite is usually not updated.

https://github.com/Microsoft/xbox-live-unity-plugin/blob/fb223e3421b13e5263618f28545301962e669387/Assets/Xbox%20Live/Scripts/UserProfile.cs#L201

**Comment by MSFT-Heba** [comment]
Hi @ilookha,
This issue will be fixed in the upcoming release.

**Comment by jplafonta** [comment]
This is fixed in 1711 release.
