### ISSUE TITLE
Detect if playing on Xbox One X

### ISSUE THREAD

**Issue by BionicPony** [Microsoft/xbox-live-unity-plugin#168]
I apologize for asking a question that isn't directly related to the Xbox Live Unity Plugin, but does anyone know a reliable (or official) way to detect if someone is playing on an Xbox One X?  I want to increase the framerate and/or other changes for One X users without making them toggle an option manually.

**Comment by XboxLiveForum** [comment]
“This is an Xbox-Live issue and we will be moving this to the MSDN forum. To following the topic please follow the link: [](https://social.msdn.microsoft.com/Forums/en-US/994f0b59-9ff5-4fb6-9aa0-4eabe5e7aaf4/)
