### ISSUE TITLE
Add support for IL2CPP builds

### ISSUE THREAD

**Issue by veleek** [Microsoft/xbox-live-unity-plugin#18]
Currently when you build using the IL2CPP Scripting Backend, Unity references the Mono C# framework libraries (e.g. mscorlib, etc.).  As a result, in order to build as IL2CPP we need a version of the Xbox C# SDK that's built entirely against the Mono runtime.  So, this won't support the current sign-in flow.  Once we have a way to get this working properly we need to make sure we support IL2CPP.

**Comment by veleek** [comment]
Currently trying to build using IL2CPP will result in the error as seen in #16.

**Comment by jasonsandlin** [comment]
Closing this and will track this internally
