### ISSUE TITLE
Can't create the XboxServices.config file

### ISSUE THREAD

**Issue by demonixis** [Microsoft/xbox-live-unity-plugin#182]
Hello,

I use the latest release of the plugin with Unity 2017.3 (.Net 3.5). I try to generate the XboxServices.config file but I get this error:

![image](https://user-images.githubusercontent.com/1017126/34159517-da6ba0fe-e4c9-11e7-9978-4e8db1c82589.png)

Any idea? Thank you.

**Comment by staceyhaffner** [comment]
This can occur when the Plugin has difficulty talking to Xbox Live. I'd recommend giving it another try and if it still doesn't work, see if you can manually add it via Windows Dev Center. Here's an article that explains the steps: https://docs.microsoft.com/en-us/windows/uwp/xbox-live/get-started-with-creators/create-and-test-a-new-creators-title

**Comment by demonixis** [comment]
I tried many time but I still have this message. I tried to create the file by myself but I'm not sure of some field. I published the game as a beta on the MS Store but the certification failed because the plugin is not able to conect to the XBox Live.

Have you another software to make this file please? Thank you.

**Comment by jplafonta** [comment]
Are you still facing this issue?

**Comment by demonixis** [comment]
Hello,

The latest version works for me (tested right now).
