### ISSUE TITLE
Canceling Login results crash rendering UserProfile unuseable

### ISSUE THREAD

**Issue by DigitalDNAGames** [Microsoft/xbox-live-unity-plugin#185]
I am making a local multiplayer game and I am using the UserProfile prefab. In this particular case I start my game and when the first login prompt comes up instead of picking a user you just cancel the login. 

Microsoft.Xbox.Services.XboxException: 'Xbox Live User object is required to be constructed by a Windows.System.User object for a multi-user application.'

At this point the script on UserProfile crashes and subsequent login request are not process, rendering the game stuck on the start screen.

I have had so many errors with this plugin like this, which cause serious stability problems. The real problem it seems is that UserProfile is very bad and handling and recovering from ordinary errors that would happen during a login. There are so many scenarios I have encounters it would be difficult to enumerate them all. Xbox rejects the login for some reason ie.e "Xbox Veto" profile is broken. Log in as a guest, broken. Log in 2 controllers with the same account broken. I am hoping that this is just some side effect of the Xbox test environment.

Worst yet these only seem to happen on the Xbox itself, where my debugging capabilities are very limited. Sorry to tack so much on this bug but I am not sure how else to get in contact with you.

**Comment by DigitalDNAGames** [comment]
This particular error (The canceling login one) is caused when 
   this.XboxLiveUser.Initialize(task.Result);
in  UserProfile.InitializeXboxLiveUser

**Comment by DigitalDNAGames** [comment]
There is another crash that occurs if you choose the "Add Guest" option in the sign in menu.

**Comment by jplafonta** [comment]
I am investigating these issues now.  I will get back to you with a fix or resolution shortly.

**Comment by jplafonta** [comment]
I made some fixes to improve the error handling.  Guest accounts are still unsupported on xbox at this time, but hopefully this will resolve some other other issues you are seeing.  You can either build from source (there are instructions on github) or look at my changes [here](https://github.com/Microsoft/xbox-live-unity-plugin/commit/037fd96c0ac6b034a780ed946b227801773a10ea) and manually update your script locally.
