### ISSUE TITLE
Guest Accounts don't seem to work at all

### ISSUE THREAD

**Issue by DigitalDNAGames** [Microsoft/xbox-live-unity-plugin#187]
Guest accounts with multiple logins enable seem to simply crash the plugin (on the Xbox). Is there some trick to getting these to work?

Again the error handling for this is horrible. The script stops running on the prefab simply stops working for the duration of the session rendering the controller useless.

**Comment by jplafonta** [comment]
This is currently not supported.  We will update our scripts to do better error handling as well as remove references to them in the scripts until they are supported.

**Comment by DigitalDNAGames** [comment]
What exactly isn't supported? Multiple Users? or Guest Accounts?

**Comment by jasonsandlin** [comment]
Guest accounts aren't yet supported for Creators games
