### ISSUE TITLE
Can't Build UWP .Net 3.5

### ISSUE THREAD

**Issue by Kazura23** [Microsoft/xbox-live-unity-plugin#188]
Hello,

I tried building through different ways but nothing is working.
I'm on Unity 2017.3.0, got all the latest Win10 SDK (10.14, 10.15, 10.16). I'm trying to build an UWP with .Net 3.5 Runtime, API compatibility 2.0, and I successfully builded an empty project which had the Xbox Live package installed.

But on my main project it doesn't work even if I configure the same checked boxes as they are in the default .dll files of the XBLpackage. I found a configuration that nearly worked for me as you can see.

![boxerrors](https://user-images.githubusercontent.com/17180657/34396780-e692d26a-eb6f-11e7-976f-7aba249f2a93.png)

And at the end, all the building loading is complete but it gives me these errors that break the build.

![error1](https://user-images.githubusercontent.com/17180657/34396801-267080ee-eb70-11e7-8bc7-9231967255ff.png)
![error2](https://user-images.githubusercontent.com/17180657/34396802-28fe40a8-eb70-11e7-8999-f7b628354439.png)

Any idea about this?

**Comment by jplafonta** [comment]
Hello @Kazura23,

It looks like you are unintentionally including some editor only dependencies in the UWP build.  Any dlls under the /Assets/Xbox Live/Libs/UnityEditor path should only ever be imported for editor and not WSAPlayer (aka UWP) as you have above.  Try excluding them for WSAPlayer and see if the errors are resolved.

**Comment by jplafonta** [comment]
I am going to close this issue since everything is working fine for me.  If you are still facing this problem reactivate.
