### ISSUE TITLE
Association Wizard Crashing

### ISSUE THREAD

**Issue by 13AMMike** [Microsoft/xbox-live-unity-plugin#19]
Running the Association Wizard in an empty project is crashing during the "Enable Xbox Live Features" state. This happens while running on an administrator account, with Unity 5.5.1 and using Windows 10 version 10.0.14393 Build 14393 as well as SDK version that is installed with the Power Shell script that is in this package.

**Comment by veleek** [comment]
Hey @13AMMike.

I noticed your question posted to the MSDN forums as well as here.  For any future questions, you don't need to worry about cross-posting.  Our team members are monitoring a few different places for questions so the same people should see it regardless of where it's posted.  :) 

Now, regarding the Association Wizard crash: Do you have any additional detail about the problem?  If you can attach a Fiddler trace, that will show us the failing calls that would be helpful in narrowing down your problem.  Alternatively, you may be able to find some errors in the event log that detail the exception that's causing the crash.  And finally, if you provide us with the App ID for the app that you're attempting to enable and we may be able to reproduce the issue locally.  You can get the app ID by going to your apps page in DevCenter and grabbing it from the URL (for example: https://developer.microsoft.com/en-US/dashboard/apps/9N4SGJRBTWH4/  < this last part is your app id).

Any one of those pieces should be good to get us started, but as many as possible is best.  We're going to be adding some better error handling and logging to the association wizard to make this easier, but for now this would be the most helpful information for us.

- Ben

**Comment by 13AMMike** [comment]
Hey @veleek,
Attached is the .saz report from fiddler. If there is something missing please let me know!

[https://drive.google.com/open?id=0B9eM3aYJ1kNjdnl0NzU2NjlYd1k](url)

As for the event log, all I could find was this call here as the program crashes:
11:27:43:7961 Fiddler.Network.ProtocolViolation - [#668] Content-Length mismatch: Request Header indicated 4,452 bytes, but client sent 0 bytes.

The AppID for the project is 9NP16QQ1T2G8.

I hope this helps!

**Comment by 13AMMike** [comment]
Hey @veleek any information about this issue? Or a possible work around for the time being?

**Comment by veleek** [comment]
Hey Mike, Sorry for the delay.  I'm still waiting on some more info from another team but I have enough to continue troubleshooting.  Are you (or the publisher that your account belongs to) already part of the ID@Xbox program or some other program?  It looks like a request is failing because your account is not valid for the Xbox Live Creators program. 

It's also possible that you requested to join the creators program and something broke in the background.

**Comment by 13AMMike** [comment]
We are part of the ID@Xbox Program and have also been set up and connected to Dev Net. If there is something broken with the account would I be able to fix that on my end?

**Comment by veleek** [comment]
Actually for the preview we don't support the creators program AND ID@Xbox at the same time.  We've got a few things that we need to fix up in the back end in order to support people who are members of both programs.

In the meantime if you want to try out Creators Program functionality you will need to create a separate account that is not associated with the ID@Xbox program.

Rest assured that we DO plan on supporting this scenario eventually.

**Comment by 13AMMike** [comment]
Hey @veleek,

Is it possible for us to create the Xbox Config file on our own that can allow us to access Xbox Live functionalities with our ID@Xbox account? We are trying to make a Play Anywhere game and not being able to work on this functionality blocks us on that end.

Also is there any ETA on when that will be supported?

**Comment by veleek** [comment]
@13AMMike, you can talk to your  ID@Xbox contact to get your title Xbox Live enabled in DevCenter using the regular ID@Xbox workflow.  After that, running through the association wizard should see the title is already enabled and setup the configuration you need.

However, if you are using this Xbox Live Unity plugin you will only be able to use the limited Creators Program functionality.  Full Tier Xbox Live support as part of this plugin is still a few months away at minimum.  

If you want to use the regular Xbox Live SDK, you should follow the [Getting Started using Unity ID@Xbox developers](https://developer.microsoft.com/en-us/games/xbox/docs/xboxlive/get-started/engines/how-to-add-xbox-live-support-to-unity-uwp-for-idxbox) documentation.
