### ISSUE TITLE
Unresolved P/Invoke method XsapiGlobalInitialize thrown with Master builds

### ISSUE THREAD

**Issue by demonixis** [Microsoft/xbox-live-unity-plugin#192]
Hello,

I use the latest stable version of Unity as well as the latest version of this plugin. When I compile a master build, I got this exception. Any idea to fix it?

```Unresolved P/Invoke method 'XsapiGlobalInitialize!Microsoft.Xbox.Services.140.UWP.C.dll' in assembly 'Microsoft.Xbox.Services.UWP.CSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' because it is not available in UWP applications. Please either use an another API , or use [DllImport(ExactSpelling=true) to indicate that you understand the implications of using non-UWP application APIs.```

Regards,

**Comment by jplafonta** [comment]
What configuration are you using? Is this a build error from the VS UWP output project or from building in Unity itself?

**Comment by demonixis** [comment]
It's from Visual Studio in a Master x64 build.

**Comment by jplafonta** [comment]
Sorry for the delayed reply.  

I tried this myself today and I am not able to repro the build error.  Do you see this error in configurations other than "master"?  If you look at the VS UWP output project do you see the dll its complaining about added as a reference like this:
![unity output](https://user-images.githubusercontent.com/11906693/35075838-3b26c170-fbaa-11e7-9fe4-d1f39273437f.PNG)

**Comment by demonixis** [comment]
Hello,
No it seems to be fine with Visual Studio. In any case, when I submit the application to the store, the certification fails. Now I use the dll provided in the repo xbox-live-api and it's fine (but I just have the login), it's up on the store.

I'll regive it a try for the next release, thank you for you time.

**Comment by Arcanebits** [comment]
Same exact issue, I May add to Demonixis:
1- Payed with .Net versions up and down in unity 1-Itself Unity 2-Microsoft Plugin with no results
Any solution?
Arcanebits

**Comment by Arcanebits** [comment]
I have a threads on MS forums, not a solutiion yet... https://social.msdn.microsoft.com/Forums/windowsapps/en-US/b8689ac7-9884-400a-a87f-3d2040871bb7/irritating-new-issue-uwp-isue-after-implementing-a-microsoft-plugin-into-my-unity3d-game-now-it?forum=xboxlivedev

I will be back and forth to replicate any importan outcome.

Arcanebits

**Comment by jplafonta** [comment]
Hello @Arcanebits,

I am still not able to reproduce this issue.  I tried searching a bit for what the cause could be and I saw some other with similar errors were able to work around them by updating to the latest windows sdk, so I recommend trying that.

**Comment by Arcanebits** [comment]
Hello @jplafonta Sadly Im already on the latest: QFE Build: 10.0.16299.91 - Released November 2017
Im at full stop, Unity3d Delivered and the game its done. I was working well until I applied the Microsoft Unity Package they made  for XBOX integration and well... im where I am.

I will see what can I tweak by myself, since this seems to be a non important issue.

![latestsdk](https://user-images.githubusercontent.com/34106553/36631633-ae459c00-1949-11e8-8c12-e568d83ef4dc.jpg)

**Comment by Arcanebits** [comment]
Any Tip?

**Comment by Arcanebits** [comment]
Hi Folks!

I know that if the issue is not blue screening millions of computers is not going to be something urgent, but please, can you at least try to help us with a work around?

We are small indie team, time is not on our side and we already had way too much PR material into this.

Anyone?

**Comment by jplafonta** [comment]
Hello @Arcanebits 

Just for reference can you try some the sample scenes with the same build configuration and see if you see this issue?

**Comment by Arcanebits** [comment]
When I was trying to isolate the problem did that, same results.
Thanks in advance
Arcanebits

**Comment by Arcanebits** [comment]
Just came by, to see if any news and to re post that I re Did all the procedure in another PC with another project, same error, also went to the previews solution (the same stuff but without the plugin) and it worked... so we are on the same exact place just cuadruple verified my side, if that can help...

**Comment by Arcanebits** [comment]
VERY IMPORTANT UPDATE!
Please Microsoft's staff validate or correct me if I'm mistaken, so not to say something wrong, and help the people in need.
I Followed this official page to make the adjustments required: https://docs.microsoft.com/en-us/windows/uwp/xbox-live/get-started-with-creators/unity-prefabs-and-sign-in
That’s the part I broke stuff, I made zillions of adjustments and nothing… today I made adjustments and quadru verified my side, then a peer trying to help me  says “you are on a not STABLE version”, then he showed me:
https://github.com/Microsoft/xbox-live-unity-plugin/releases/tag/v1711 and
https://github.com/Microsoft/xbox-live-unity-plugin/releases
I WAS LINKED TO A PREVIEW VERSION BY THE OFFICIAL DOCUMENTATION.
I went to the Unity Project, deleted / installed *its keep the configuration so not so much pain there*
Exported, opened in VS and IT RAN,
Now to sleep tomorrow I will see if IT passes the self-tests and upload for approval!
Cheers!!
Arcanebits

**Comment by jplafonta** [comment]
Hello @Arcanebits 

Glad you were able to resolve your issue. If you do not require il2cpp scripting backend, older versions (1711 and before) should be great, but we only added support for il2cpp in the 1802 release.  I am going to leave this as an open issue and try to investigate more this week since it seems like @demonixis also hit this issue and needs il2cpp support.

**Comment by Arcanebits** [comment]
Issue Still Open, Alive and still breaking my head... 
If the code pass a second time to the plugin, it breaks...

Help needed..

**Comment by XboxLiveForum** [comment]
Hello @Arcanebits can you retry and let us know if you are still facing this issue?

**Comment by Arcanebits** [comment]
Yes. solved thanks.

**Comment by ioapps-dev** [comment]
I have the same problem, I have been trying to solve this problem for days:

Exception produced: 'System.DllNotFoundException' in Microsoft.Xbox.Services.UWP.CSharp.dll
An exception of type 'System.DllNotFoundException' occurred in Microsoft.Xbox.Services.UWP.CSharp.dll but was not controlled in the user's code
Additional information: Unable to load DLL 'Microsoft.Xbox.Services.140.UWP.C.dll': Unable to find the specified module. (Exception from HRESULT: 0x8007007E)
