### ISSUE TITLE
Issues with 2017.3.0p3 patch for UWP build

### ISSUE THREAD

**Issue by Machaira** [Microsoft/xbox-live-unity-plugin#194]
I've tried using both .NET 3.5 and 4.6 with the newest Unity patch and this package. 3.5 gives me a ton of errors:

Assets/Xbox Live/Scripts/UnityTaskExtensions.cs(5,24): error CS0234: The type or namespace name `Tasks' does not exist in the namespace `System.Threading'. Are you missing an assembly reference?
Assets/Xbox Live/Scripts/UserProfile.cs(9,24): error CS0234: The type or namespace name `Tasks' does not exist in the namespace `System.Threading'. Are you missing an assembly reference?
Assets/Xbox Live/Scripts/Leaderboard.cs(71,13): error CS0012: The type `System.Object' is defined in an assembly that is not referenced. Consider adding a reference to assembly `System.Runtime, Version=4.0.20.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
Assets/Xbox Live/Scripts/Leaderboard.cs(81,13): error CS0012: The type `System.Collections.Generic.IEnumerable`1<Microsoft.Xbox.Services.Social.Manager.XboxSocialUser>' is defined in an assembly that is not referenced. Consider adding a reference to assembly `System.Runtime, Version=4.0.20.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
Assets/Xbox Live/Scripts/Leaderboard.cs(81,13): error CS0012: The type `System.Collections.IEnumerable' is defined in an assembly that is not referenced. Consider adding a reference to assembly `System.Runtime, Version=4.0.20.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
Assets/Xbox Live/Scripts/UnityTaskExtensions.cs(11,57): error CS0246: The type or namespace name `Task' could not be found. Are you missing an assembly reference?
Assets/Xbox Live/Scripts/UnityTaskExtensions.cs(21,75): error CS0246: The type or namespace name `Task' could not be found. Are you missing an assembly reference?
Assets/Xbox Live/Scripts/UnityTaskExtensions.cs(40,33): error CS0246: The type or namespace name `Task' could not be found. Are you missing an assembly reference?
Assets/Xbox Live/Scripts/UnityTaskExtensions.cs(60,12): error CS0246: The type or namespace name `Task' could not be found. Are you missing an assembly reference?
Assets/Xbox Live/Scripts/UnityTaskExtensions.cs(87,33): error CS0246: The type or namespace name `Task' could not be found. Are you missing an assembly reference?
Assets/Xbox Live/Scripts/UnityTaskExtensions.cs(91,16): error CS0246: The type or namespace name `Task' could not be found. Are you missing an assembly reference?
Assets/Xbox Live/Scripts/UserProfile.cs(102,64): error CS0012: The type `System.EventArgs' is defined in an assembly that is not referenced. Consider adding a reference to assembly `System.Runtime, Version=4.0.20.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

4.6 gives me just one:

Assets\Xbox Live\Scripts\UserProfile.cs(148,49): error CS0234: The type or namespace name 'UserPicker' does not exist in the namespace 'Windows.System' (are you missing an assembly reference?)

Any ideas would be welcome.

**Comment by Machaira** [comment]
OK, it looks like I wasn't hitting the correct SDK version. The UserPicker needs a version of at least 10.0.14393.0. :\

**Comment by jplafonta** [comment]
It seems like you figured it out, but for 3.5 you will have to change the import settings.  4.6 should work but as you realized it looks like you need a different version of the sdk.

**Comment by JasonHein** [comment]
I'm using the latest SDK version and am getting these errors with 3.5.

What import settings do I need to change, and what do I need to change them to?

**Comment by Machaira** [comment]
Why not just switch to 4.6?
