### ISSUE TITLE
Missing Dll 

### ISSUE THREAD

**Issue by salvobunetto** [Microsoft/xbox-live-unity-plugin#195]
When i build for ARM i get this missing Microsoft.Xbox.Services.140.UWP.C.dll from plugins/ARM/ folder
x64 and x86 have this dll and all works fine

**Comment by jplafonta** [comment]
Hello @salvobunetto 

ARM is not supported. We do have an ARM configuration for that dll, but it has not been tested and we don't support ARM for some other dependencies.  What device do you need ARM support for?

**Comment by salvobunetto** [comment]
Hi @jplafonta

I have a game that currently has as Target UWP, taking advantage of this plugin but I see myself unable to do a build for ARM for the lack of this DLL, I would not separate the project in one dedicated to arm (without Xbox Live) and one for x86/x64 (with Xbox Live) so I Wonder how do I ignore this plugin when I do the build for ARM?

**Comment by jplafonta** [comment]
It should be simple enough for us to create a version of the plugin that contains the arm dll.  Stay tuned and I will try and get a fix for you shortly.

**Comment by salvobunetto** [comment]
@jplafonta Thank you 👍

**Comment by jplafonta** [comment]
I've rebuilt a package that includes the arm binaries.  We will include them in future releases as well, but for now use this:

[XboxLive.zip](https://github.com/Microsoft/xbox-live-unity-plugin/files/1704389/XboxLive.zip)
