### ISSUE TITLE
Deployment Error. Il2cpp with the beta xbox plugin!

### ISSUE THREAD

**Issue by ayubhassan** [Microsoft/xbox-live-unity-plugin#196]
Ok i am getting this error whenever I deploy the project; 
-Exception thrown: write access violation. **__this** was nullptr. occurred in __this->set_appConfig_5(L_4);

**Comment by jplafonta** [comment]
Hello @ayubhassan 

Can you provide a little more context? What is the project trying to do?  A callstack may also be helpful to debug.
