### ISSUE TITLE
beta plugin error in unity

### ISSUE THREAD

**Issue by prgrmr25** [Microsoft/xbox-live-unity-plugin#197]
KeyNotFoundException: The given key was not present in the dictionary.
System.Collections.Generic.Dictionary`2[System.String,Microsoft.Xbox.Services.Statistics.Manager.StatisticValue].get_Item (System.String key) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Collections.Generic/Dictionary.cs:150)
Microsoft.Xbox.Services.Statistics.Manager.MockStatisticManager.GetStatistic (Microsoft.Xbox.Services.XboxLiveUser user, System.String statName)
IntegerStat.HandleGetStat (Microsoft.Xbox.Services.XboxLiveUser user, System.String statName) (at Assets/Xbox Live/Scripts/Stats/IntegerStat.cs:21)
StatBase.<Update>m__0 (System.Object sender, .XboxLiveUserEventArgs args) (at Assets/Xbox Live/Scripts/Stats/StatBase.cs:67)
StatsManagerComponent.OnLocalUserAdded (Microsoft.Xbox.Services.XboxLiveUser user) (at Assets/Xbox Live/Scripts/Stats/StatsManagerComponent.cs:74)
StatsManagerComponent.Update () (at Assets/Xbox Live/Scripts/Stats/StatsManagerComponent.cs:51)

**Comment by rakhad** [comment]
Thanks for pointing this out. We'll address it in the next release.

In the meantime you can edit IntegerStat.HandleGetStat to look like this
```
    protected override void HandleGetStat(XboxLiveUser user, string statName)
    {
        this.isLocalUserAdded = true;
#if UNITY_EDITOR
        this.Value = 10;
#else
        StatisticValue statValue = XboxLive.Instance.StatsManager.GetStatistic(user, statName);
        if (statValue != null)
        {
            this.Value = statValue.AsInteger;
        }
#endif
    }
```
