### ISSUE TITLE
Xbox Live sign-in error in UWP game

### ISSUE THREAD

**Issue by Machaira** [Microsoft/xbox-live-unity-plugin#198]
So I'm getting this error - 

![xboxliveerror](https://user-images.githubusercontent.com/1019165/35456781-af4f97c4-02a4-11e8-8fa9-7ecebb7637eb.png)

Any ideas why I can't sign in using the prefab when I'm already signed-in to the Xbox app?

**Comment by jplafonta** [comment]
DC12 is a content isolation error. Have you the the xbox live association wizard to associate your Unity project with and xbox live enabled game?  Make sure you do that, and also make sure you are running in the sandbox associated with your game.  There are more detailed instruction on how to get set up with xbox live [here](https://docs.microsoft.com/en-us/windows/uwp/xbox-live/get-started-with-creators/configure-xbox-live-in-unity).

**Comment by Machaira** [comment]
I did this. I am running my machine in Developer mode, but I built the project as a Development build. I'm assuming this is the way to do it. If not, do I have to switch my machine back to Retail mode?

**Comment by ayubhassan** [comment]
are you using the beta plugin?

**Comment by Machaira** [comment]
Not unless the Download button on the home page downloads it.

**Comment by aablackm** [comment]
Hi Machaira have you [Setup your App for test in the Windows Dev Center](https://imgur.com/nmuKBMq)?
In those steps make sure you have [setup an authorized test account](https://imgur.com/RlDC4hr).

**Comment by Machaira** [comment]
All done. Test account uses the email tied to my Xbox account. I don't think I'm missing anything unless it's something not well-documented.

**Comment by aablackm** [comment]
Just double checking. When [hitting the Test Button](https://imgur.com/a/J7Czd) did you make sure you saw the Publishing and Success dialogue below the button? https://imgur.com/a/J7Czd

**Comment by Machaira** [comment]
Yes, publishing was successful.

**Comment by aablackm** [comment]
I see you closed this thread. Were you able to sign-in successfully?

**Comment by cjSEG6** [comment]
Has anyone found a solution to this problem, I can’t find an answer anywhere

**Comment by cjSEG6** [comment]
Hi, I just checked the XboxService.config file again and its correct and development mode is on. I've also assured that the authorized dev account is the one being used and the Xbox live settings for the game have been published. Still, I encounter the same problem when attempting to sign in using the PlayerAuthentication prefab.
