### ISSUE TITLE
After inserting this tons of

### ISSUE THREAD

**Issue by Arcanebits** [Microsoft/xbox-live-unity-plugin#199]
Awake()' is marked as an override but no suitable method found to override
I dont need everything just the login and show gamertag capabilities
Anyone have solves this?
Arcanebits

**Comment by Machaira** [comment]
You're going to have to provide more detail. Can you post all of the relevant code?

**Comment by jplafonta** [comment]
Closing this issue for now. If you can provide more info we might be better able to help.
