### ISSUE TITLE
write access violation error!

### ISSUE THREAD

**Issue by prgrmr25** [Microsoft/xbox-live-unity-plugin#200]
Ok when my project deploys after the unity splashscreen, i get the following error and it breaks;

`Unhandled exception thrown: write access violation.
**__this** was nullptr. occurred` in Bulk_Microsoft.Xbox.Services.UWP.CSharp_0.cpp  and this happens in line 20120 where it says `__this->set_appConfig_5(L_4);`
Am using the beta plugin. 

debug error;
`Run-Time Check Failure #0 - The value of ESP was not properly saved across a function call.  This is usually a result of calling a function declared with one calling convention with a function pointer declared with a different calling convention.`

debug callstack;
`GameAssembly.dll!SocialManager_SocialManagerDoWork_m1711937723(Il2CppObject * __this, unsigned int * ___numOfEvents0, const MethodInfo * method) Line 14347	C++	Symbols loaded.`

**Comment by XboxLiveForum** [comment]
Hello, prgrmr25.

We need a bit more information about your request.
Please provide the required general information

What platform is the issue happening on (XDK, or UWP)?
What XSAPI project flavor are they using (C++, WinRT)?
What XSAPI version are they using (1612, 1703, etc)?
What OS or XDK are they using? (XDK 1703, TH2, etc)
Additional Helpful Information

What error code was encountered?
Perhaps a fiddler trace where possible?

Once we have these details, we might have a better idea of which direction to take this investigation.

Thanks!

**Comment by prgrmr25** [comment]
I am using the 1802 prerelease unity plugin for creators program. I built the project as an il2cpp project in unity for UWP then I opened the project in visual studio and built it, then when it builds and the unity splash screen shows, it breaks and i get the errors above.
I am deploying the project on my computer running windows 10.

**Comment by prgrmr25** [comment]
#update: This error seems to only occur when i build for x86 but, no errors when it's x64!

build options;
x86, master, local machine

**Comment by jplafonta** [comment]
Hello @prgrmr25 

I am trying to reproduce the issue locally with some of our example scenes but so far I have not been able to.  Since the call stack/code you shared is generated by Unity's il2cpp build system, its hard to say exactly what could be going wrong. I did notice that the generated code you shared looks a bit different than what I am using, so maybe that could be part of the problem.  I am running Unity 2017.2.0p2.  Could you please try with this version of Unity?  It may also be helpful to know if you see this issue with our sample scenes as well.

**Comment by prgrmr25** [comment]
just tested it again with the latest version of unity(2017.3.1) and visualstudio(2017 5.6), and i still get the same error.  `Run-Time Check Failure #0 - The value of ESP was not properly saved across a function call.  This is usually a result of calling a function declared with one calling convention with a function pointer declared with a different calling convention.
`

**Comment by jplafonta** [comment]
@prgrmr25 Sorry for the delayed response.  Could you please try with the Unity version I mentioned (not latest). We have seen some issues with the latest version that were not present on the version I mentioned above.

**Comment by jplafonta** [comment]
I finally investigated and resolved this issue.  Was a problem with the pinvoke calling convention that apparently only affected some il2cpp configurations.  The fix will be in master soon and then in our next release.
