### ISSUE TITLE
2017.3.0p4 .NET 4.6 version compile errors

### ISSUE THREAD

**Issue by Machaira** [Microsoft/xbox-live-unity-plugin#201]
Created a brand new project with just the Xbox Live package. Switched to use .NET 4.6 and set the correct DLLs. Dropped the Leaderboard prefab into the scene, set the stat to one already configured and for the PC Windows build get the following:

![xbox live error](https://user-images.githubusercontent.com/1019165/35626994-8970330a-0665-11e8-9a90-2915dc9ae4a6.png)

Any ideas why this stuff doesn't just work? I have issues also with the UWP build which I've posted already.

**Comment by jplafonta** [comment]
What platform are you targeting and what version of Unity are you using?

**Comment by Machaira** [comment]
Sorry, thought I'd put the platform in there. Edited the post. I'm targeting PC Windows. Unity version is in the title, the latest patch release.

**Comment by jplafonta** [comment]
Switch the target platform to UWP in build settings. Scripting backend should be .NET. Everything else looks ok.

**Comment by Machaira** [comment]
I don't want a UWP build, I want a regular PC build.

**Comment by jasonsandlin** [comment]
The Xbox Live Creators Program only supports UWP builds.  

More detail can be found here: https://docs.microsoft.com/en-us/windows/uwp/xbox-live/developer-program-overview#xbox-live-creators-program
