### ISSUE TITLE
Manually filling in configs and entering the TitleId in it's hex format causes unclear error

### ISSUE THREAD

**Issue by NicholasLebrun** [Microsoft/xbox-live-unity-plugin#207]
The TitleId is given in hex format in the title's settings in xdp.xboxlive.com. Entering the hex format in the XboxServices.config will cause an error when deserializing, which is caught silently and hard to debug.

I had to debug into xbox-live-unity-plugin\CSharpSource\Source\Microsoft.Xbox.Services.UnityEditor.CSharp\Common\XboxLiveAppConfiguration.cs's Load method to understand the issue. A better error handling would be appreciated.

**Comment by jplafonta** [comment]
Thanks for raising this. We will address this in the next release.

**Comment by prgrmr25** [comment]
vc Add addisplayer.cs

**Comment by prgrmr25** [comment]
xs gamemanager.cs
