### ISSUE TITLE
Build post process fails on ILCPP

### ISSUE THREAD

**Issue by GregLukosek** [Microsoft/xbox-live-unity-plugin#210]
With latest release Unity Post Process build fails on finding the correct path to the project.

Looks like file extension isnt set correctly for IL2CPP.

In previous releases XBoxLivePostProcessing.cs contained this. now its removed

            string projectFile = null;
            if (scriptingBackend == ScriptingImplementation.WinRTDotNET)
            {
                projectFile = Path.Combine(projectFolder, Application.productName + ".csproj");
            }
            else if (scriptingBackend == ScriptingImplementation.IL2CPP)
            {
                projectFile = Path.Combine(projectFolder, Application.productName + ".vcxproj");
            }

**Comment by jplafonta** [comment]
Which release are you using?  This check (and support for il2cpp) was only added in the 1802 preview release and I don't think it has been removed.

**Comment by XboxLiveForum** [comment]
Hi @GregLukosek Were you able to resolve this issue? Please let us know if you still need assistance. Thanks!

**Comment by GregLukosek** [comment]
Sorry for late reply. Imported prerelease version 1802 and it’s working correctly now with IL2CPP and .net 4.6

My suggestion would be to mark this support a bit better In documentation. Other than that excellent work on the Unity plugin. Very easy to integrate.
