### ISSUE TITLE
Sign out then sign back in

### ISSUE THREAD

**Issue by craigBuxton** [Microsoft/xbox-live-unity-plugin#214]
First I use the SignInAndProfile prefab in my application (SUA) and sign in to XBL, the ProfileInfo updates to reflect the fact that I am logged in. Then I go to the Xbox app and sign-out. If I then return to my app the 
ProfileInfo reverts to "Add User", when I click the SignInButton, I get the sign-in UX, but then this error in the plugin debug console when trying to login the same user:

Argument Exception: An item with the same key has already been added. Key Microsoft.Xbox.Services.XboxLiveUser

It seems like details of previous user should have bee set to null when sign-out was completed. What am I missing?

![image](https://user-images.githubusercontent.com/33639945/37729891-38753982-2d0c-11e8-938c-b0b59dc8e136.png)

**Comment by XboxLiveForum** [comment]
Hi Craig,
Thank you for positing on GitHub. We have a few questions for you.

1.What engine are you using (if any) and what version?
2.What version of Xbox Live are you using?
3.What IDE (i.e. Visual Studio) are you using and what version?
4.What version of the Windows SDK are you using?”

Thank You,
Brett

**Comment by XboxLiveForum** [comment]
Hi Craig,
I am checking in to see if you were able to the requested information above. Please let us know.

Thank You,
Brett

**Comment by MSFT-Heba** [comment]
Hi @craigBuxton We believe this issue has been fixed in the latest releases. Since we haven't heard back from you in a while, we'll go ahead and close this issue. Please feel free to reopen or create a new issue as needed.
