### ISSUE TITLE
Signing Out of Xbox Live in game

### ISSUE THREAD

**Issue by CheeseBrownie** [Microsoft/xbox-live-unity-plugin#215]
I'm being told my Microsoft when I'm submitting my app to the store that I need to allow users to sign in and out of their Xbox Live account while in game. I got the sign in functionality working from using the UserProfile.cs script from the examples, but there doesn't seem to be any reference to signing out. I see that in UserProfiles there's an EventHandler for Microsoft.Xbox.Services.XboxLiveUser.SignOutCompleted but nowhere does it show how to actually sign out.

**Comment by MSFT-Heba** [comment]
@CheeseBrownie Not sure if you've already seen this, but the new [v1804 release of the Xbox Live Unity Plugin](https://github.com/Microsoft/xbox-live-unity-plugin/releases/tag/v1804) that introduces a new authentication prefab (PlayerAuthentication) that should handle both sign in and sign out for you. Would you mind giving that a try and let us know how it worked for you?

**Comment by XboxLiveForum** [comment]
Hi CheeseBrownie,

I am checking to see if you were able to resolve your issue. 

Kam - Xbox Live Forum Moderator.

**Comment by XboxLiveForum** [comment]
Hi CheeseBrownie,

Since we haven't heard back from you, we will close this support request. If you are still encountering an issue, please let us know and we will reopen this and investigate further.

Thank you!
