### ISSUE TITLE
Unity.Tasks.dll

### ISSUE THREAD

**Issue by iPickles** [Microsoft/xbox-live-unity-plugin#219]
I am using Unity 2017.4 (Tested on 2017.2.0p2, and 2018 and got the same results)
.NET backend (4.6)

When importing the unitypackage, I get several

> error CS0433: The imported type `System.Threading.Tasks.Task' is defined multiple times

After following the partial solution here:
https://github.com/Microsoft/xbox-live-unity-plugin/issues/94
I realized that.NET 4.5+ does not need the Unity.Tasks.dll file, but after removing it I get 

> Assets/Xbox Live/Scripts/UserProfile.cs(192,88): error CS0012: The type \`System.Threading.Tasks.Task\`1<Microsoft.Xbox.Services.SignInResult>' is defined in an assembly that is not referenced. Consider adding a reference to assembly `Unity.Tasks, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'

The issue I linked above also found this problem, but they wrote that on 2017.2.0p2 it was solved, I've tried it on 2017.2.0p2 and 2018 as well as my original 2017.4, and I got the same results

Is there anything I can do to solve it?

Thanks!

**Comment by toncho11** [comment]
Hi,

I have a similar problem with Unity 2017.4 LTS in UnityTaskExtensions.cs:

For example method declaration: public static TaskYieldInstruction AsCoroutine(this Task task) gives this error:

Error	CS0433	The type 'Task' exists in both 'Unity.Tasks, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' and 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'	Assembly-CSharp

or this:

Error	CS0433	The type 'Task<T>' exists in both 'Unity.Tasks, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' and 'mscorlib, Version=4.0.0.0, Culture=neutral, 

I can not compile the asset in my project. Please assist.

**Comment by jplafonta** [comment]
Depending on which version of .NET you are using you need to include/exclude certain dlls from your build.  There is more information about this here: https://docs.microsoft.com/en-us/windows/uwp/xbox-live/get-started-with-creators/configure-xbox-live-in-unity#import-the-unity-plugin

**Comment by iPickles** [comment]
Thanks for the replay!
I should have mention that, but yea, I found that as well, I followed the instructions but it didn't make the error go away

**Comment by iPickles** [comment]
No, as I've written on the original post I'm on .NET
You say that it should work with IL2CPP? I guessed I missed it being mentioned, I will try and test it asap and report back

Thanks!

**Comment by MSFT-Heba** [comment]
@iPickles and @toncho11 If you check out this article over here, it shows which combinations of Scripting backend and Runtime versions are supported by the Xbox Live Unity Plugin. I think this might help: https://docs.microsoft.com/en-us/windows/uwp/xbox-live/get-started-with-creators/configure-xbox-live-in-unity

As you can see, if you want to use .NET 4.6 with the plugin, you need to use IL2CPP for the scripting backend.

**Comment by iPickles** [comment]
@MSFT-Heba Thanks for the info.
Sorry its taking long, I haven't built for il2cpp on uwp before.

So I got something weird happening...
I've opened a clean project for this, so none of my code should interfere. 
I was following the article you suggested, and I was able to compile in editor.
When I attempt to build the project, I get this error

`FileNotFoundException: Could not find file "{PATH_TO_BUILD}\{PROJECT_NAME}\{PROJECT_NAME}.csproj".`

BUT, there is a visual studio project on the build folder (even that Unity says the build failed)
I can pack it for xbox, and upload it without a problem, but on the xbox I get an error message saying 

`Unable to finx XBox Live app configuration file XboxServices.config ` 

Am I missing something?

**Comment by XboxLiveForum** [comment]
Hi iPickles,

Since we haven't heard back from you, we will close this support request. If you are still encountering an issue, please let us know and we will reopen this and investigate further.

Thank you!

**Comment by HudsonSchumaker** [comment]
Hello, 
I am having the issue Library\PackageCache\com.unity.textmeshpro@2.0.1\Scripts\Editor\TMP_PackageUtilities.cs(310,17): error CS0433: The type 'Task' exists in both 'Unity.Tasks, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' and 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'

**Comment by cookiedot** [comment]
Hello,
I've the same issue...  My game runs with Unity 2019-3-10f1, try to import the xbox live package and get errors.
I've do all the required things (check 4.6/uncheck 3.5 Dll).. In initial configuration i've the error with textmeshpro.
when i delete textmeshpro i've these errors: "**Assets\Xbox Live\Scripts\UnityTaskExtensions.cs(93,20): error CS0433: The type 'Task<T>' exists in both 'Unity.Tasks, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' and 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089**'"
What can i do? 1 year of hard work on my game and i can't add requested sign in of Xbox live to publish it... :'(

**Comment by Eloren1** [comment]
r u dumb xbox devs
