### ISSUE TITLE
Unable to build from source.

### ISSUE THREAD

**Issue by johnrlisenby** [Microsoft/xbox-live-unity-plugin#220]
Hello,

I'm trying to build the plugin from the source files, but I'm getting an error in PowerShell
![powershell error](https://user-images.githubusercontent.com/24777531/38152246-5f1f51c0-3456-11e8-9049-8e53adbcf300.PNG)
. I have almost everything installed in Visual Studios 2017. 
![vs](https://user-images.githubusercontent.com/24777531/38152294-a66dad38-3456-11e8-8b1c-fab0c330494d.PNG) 

Am I missing something?

Thanks,
John

**Comment by XboxLiveForum** [comment]
Hi John,

Thank you for posting on the GitHub forum. Can you provide us with some additional information:

• What platform is the issue happening on (XDK, or UWP)?
• What XSAPI project flavor are they using (C++, WinRT)?
• What XSAPI version are they using (1612, 1703, etc)?
What OS or XDK are they using? (XDK 1703, TH2, etc)

Kam - Xbox Live Forum Moderator

**Comment by johnrlisenby** [comment]
Hi,
The Xbox-live-unity-plugin . I am trying o get the source to compile from the directions, but I am getting the above error. I'm on Win10 pro 64bit and Using Visual Studios 2017 15.6.4

John

**Comment by XboxLiveForum** [comment]
Hi John,

I am going to forward this issue to our team for an investigation. 

Kam- Xbox Live Forum Moderator

**Comment by johnrlisenby** [comment]
Hi Kam,
Thanks
John

**Comment by MSFT-Heba** [comment]
Hi @johnrlisenby Would you please give the latest code in master a try?

**Comment by johnrlisenby** [comment]
Hi,
Nope still getting errors.`
[Microsoft.Xbox.Services.CSharp.sln.msbuild.errors.log](https://github.com/Microsoft/xbox-live-unity-plugin/files/1949159/Microsoft.Xbox.Services.CSharp.sln.msbuild.errors.log)
[Microsoft.Xbox.Services.CSharp.sln.msbuild.log](https://github.com/Microsoft/xbox-live-unity-plugin/files/1949160/Microsof
![error](https://user-images.githubusercontent.com/24777531/39277938-f8417304-48df-11e8-8150-12ada22fa14a.PNG)
t.Xbox.Services.CSharp.sln.msbuild.log)

`

**Comment by MSFT-Heba** [comment]
Hi @johnrlisenby Wanted to update you. We still haven't been able to repro this issue on our side. Missing the Microsoft.Cpp.Default.props usually indicates missing one prerequisite.

To double check;

- What version of Unity do you have installed? 

- When installing Unity, did you verify that these two components were installed? They are needed by the system to build the plugin:
         - Microsoft Visual Studio Tools for Unity
         - Windows Store .NET Scripting Backend (and probably IL2CPP as well)

- Also did you also install [Xbox Live Platform Extensions SDK](http://aka.ms/xblextsdk)?

**Comment by XboxLiveForum** [comment]
Hi Johnrlisenby,

I am checking in to see if you are still experiencing this issue. If you are, can you provide the following information?

What version of Unity do you have installed?
When installing Unity, did you verify that these two components were installed? They are needed by the system to build the plugin:
- Microsoft Visual Studio Tools for Unity
- Windows Store .NET Scripting Backend (and probably IL2CPP as well)
Also did you also install Xbox Live Platform Extensions SDK?

Kam - Xbox Live Forum Moderator

**Comment by johnrlisenby** [comment]
Hello,

I tried once again the other day and had the same issue. I will try later to day. I have everything updated in Visual Studios (everything checked) and have Windows Store .Net and IL2CPP Unity. I installed the latest Xbox Live SDK.

I will record / take screenshots of what I have and what I'm doing from start to finish. Who knows I might just be doing something wrong or missing a step.

Thanks,

John

**Comment by XboxLiveForum** [comment]
Hello, johnrlisenby.

Do we have any update?
Please let us know.

Thanks!

**Comment by XboxLiveForum** [comment]
Hello, johnrlisenby.

Since we did not hear from you in last 7 days.
We will be marked as an answer for now.
Please feel free to contact us again, if anything needs from us.

Thanks!

**Comment by krychaszek** [comment]
Hello,
I'm getting the same issue when I run .\build\Setup.ps1 command.

However after putting VCTargetsPath to: C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\v140 I get this errors: 

![image](https://user-images.githubusercontent.com/18212706/55241854-50493080-523c-11e9-98a2-5cc954c34242.png)

Could you help with that?

Thanks

**Comment by XboxLiveForum** [comment]
--- XDP Tier 1 Support
++@Xbox Live SDK Support<mailto:xblsdksupport@microsoft.com>

Hello Team,

Thank you for contacting XBL SDK Support. We have created a ticket to track this issue. Ticket # 21014670<https://microsoft.visualstudio.com/DefaultCollection/Xbox/_workitems/edit/21014670>.

Thank you,
Art Diaz (Protiviti Inc)
XBL SDK Support Team

**Comment by krychaszek** [comment]
Hello,

I don't understand the message. I can't open the ticket because I don't have access.
Will you answer me in this thread or should I create a new one which is not closed?

Best regards
