### ISSUE TITLE
Build error with Mixer Plugin

### ISSUE THREAD

**Issue by johnrlisenby** [microsoft/xbox-live-unity-plugin#225]
Hello,

I'm getting errors building both with Mixer and Xbox Live plug-in. I posted on their GitHub the issue, and was redirected back here. You can see the GitHub post [here](https://github.com/mixer/interactive-unity-plugin/issues/66#issuecomment-377933765).

Error: `Assets\MixerInteractive\Source\DLLs\Websocket.cs(274,10): error CS0433: The type 'MonoPInvokeCallbackAttribute' exists in both 'Microsoft.Xbox.Services.UWP.CSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' and 'UnityEngine.CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null`

Thanks ,

John

**Comment by XboxLiveForum** [comment]
Hi John,

Could you please provide the following:
1. Which version of XSAPI are you using (i.e. 1612, 1703, etc.)?
2. Which IDE and version?
3. Version of Windows SDK?
4. If possible, steps for reproducing the issue (aside from what is already posted in the linked thread.)

Thanks

**Comment by johnrlisenby** [comment]
Hi,
Sorry, I'm currently using Xbox Live plugin 1802 (Preview Release), current Mixer Plugin for Unity's Asset Store, Visual Studios 2017, Windows SDK 16299.0, and I'm using the current version of XSAPI. (How to I check?)
Steps:
•	Import: Unity Xbox Live plug-in (1802)
•	Import Mixer Interactive plug-in from the store.
•	Switch support for IL2CPP NET4.5 (uncheck editor DLLs in XboxLive/ lib/UnityEditor/NER35 folder, and check editor for all DLLS (4). From Directions [here](https://docs.microsoft.com/en-us/windows/uwp/xbox-live/get-started-with-creators/configure-xbox-live-in-unity).
•	Check editor in DLLs (2) in XboxLive/ lib/UnityEditor/NET45
•	There will be error with Newtonsoft.Json (two in project) I unchecked the Editor one in Mixer/DLL/source/ Win32.
•	Then Build out
•	Should get errors(4) with websocket.cs as listed above
I added #if UNITY_XBOXONE on the errors.
Example
`#if UNITY_XBOXONE
        [MonoPInvokeCallback(typeof(OnConnectDelegate))]
#endif`
Rebuild and it should all work. I have tested within my game.

I hope this helps,

John

**Comment by XboxLiveForum** [comment]
Hi John,

No problem, thank you for providing these details. I will put in a request for someone on our team to look into this. There could be some delay. We appreciate your patience in the meantime.

Thanks!

**Comment by MSFT-Heba** [comment]
Hi @johnrlisenby This is definitely a bug. We've added this to our backlog.

**Comment by XboxLiveForum** [comment]
Hi John,
The support team is currently working on this request. We will continue to provide updates until resolution.
Thank you

**Comment by XboxLiveForum** [comment]
Hi John,
The support team is currently working on this request. We will continue to provide updates until resolution.

**Comment by XboxLiveForum** [comment]
Hi,
The support team is currently working on this request. We will continue to provide updates until resolution.

**Comment by XboxLiveForum** [comment]
Hi John,
The support team is currently working on this request. We will continue to provide updates until resolution.

**Comment by XboxLiveForum** [comment]
Hi John,
The support team is currently working on this request. We will continue to provide updates until resolution.

**Comment by reigota** [comment]
Any solution???

**Comment by cjjeffer** [comment]
Hi, has there been any update on this issue? My game is relying on Unity's burst compiler which calls on the 
 MonoPInvokeCallbackAttribute defined in UnityEngine.CoreModule which is of course conflicting with the one defined by the Xbox Live plugin.

**Comment by atrivedi** [comment]
Hello! We are having the same issue

```
The type 'MonoPInvokeCallbackAttribute' exists in both 'Microsoft.Xbox.Services.UnityEditor.CSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' and 'UnityEngine.CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
```

Is there an update here. We're using [this](https://github.com/Microsoft/xbox-live-unity-plugin/releases/tag/v1804qfe3) version of Xbox Live API

Thank you.

**Comment by MSFT-Heba** [comment]
Hey everyone,
A quick update. We've posted an announcement that integrating Xbox Live is no longer a requirement for UWP games to be published on Xbox as part of the Creators Program and we are phasing out software needed to support Xbox Live on UWP. 

For more details: https://github.com/microsoft/xbox-live-unity-plugin#2021-update-more-accessible-creators-program-no-longer-requires-xbox-live
