### ISSUE TITLE
Sign out crash (1804) 

### ISSUE THREAD

**Issue by JorgeRamonPuig** [Microsoft/xbox-live-unity-plugin#233]
Hello everyone,

I'm developing a game for Windows 10 and Xbox One (UWP) with Unity 2017

I'm trying to integrate the Xbox live plugin (1804)  and works partially on PC and Xbox One:

- Sign In **works**
- Leaderboards **works**
- System sign out **crash**

When I try to sign out (from the system not from the game) the game crashes without error.

I need to implement the sign out button in my app but I don't know why the game crashes if the user sign out from the system.

Any idea? 

Do you know if I need to add something in the game to check if the user is sign out from the system (not from the game) ?

 I'm using Visual Studio 2017 version 15.6.7 and Unity 2017.4.2f2.

Thanks to all, and great job with this plugin.

**Comment by JorgeRamonPuig** [comment]
Thanks Brett,

My SDK version is 10.0.16299.0.  

Do you know if I need to update my SDK to the last version April 2018?

I read the documents and I will try to fix it. (or test the sign out functions and try to find the error)

Thanks,
Jorge

**Comment by JorgeRamonPuig** [comment]
Hello again,

I'm trying to use the function **Sign Out** inside PlayerAuthentication.cs script:

        public void SignOut()
        {
            this.playerNumberText.color = Color.white;
            this.StartCoroutine(SignInManager.Instance.SignOutPlayer(this.PlayerNumber));
        }

I've changed the function type private to public ( to use it in a button in my game) 

When I use this function appear this warning:

_An exception occured in SignInManagerof type: MinimumPlayerNumberReached Details: Remove User Failed: At least one player should be signed in. Player 1 is the last signed in player._

What it means? It's not possible to sign out? or maybe I need to clean all the information about the signed in user, not only sign out. Maybe clean the **xboxLiveUser** variable or something like that?

This message appears when I test it inside Unity editor.

After check the code I found inside **SignInManager.cs**  the function  **public IEnumerator SignOutPlayer(int playerNumber)** not allow to sign out the player 1.

I tested it in Xbox One and nothing happens, never sign out the user using this function and I don't know how to check when the user sign out from the system. 

Thanks again,
Jorge

**Comment by MSFT-Heba** [comment]
@JorgeRamonPuig There is a requirement that at least one XboxLiveUser/Player should be signed in. So what you're seeing is happening because you're trying to sign out the last remaining player.

**Comment by JorgeRamonPuig** [comment]
Hi @MSFT-Heba,

But, a user can sign out from Xbox One system. I need to catch it  and show a message or restart the game without sign in information, right?

I made a test and I changed the if condition to allow the last user to Sign Out from the app and works.

Everything looks ok and appear again the sign in button. Also, If I sign in with the same user, works. But if I sign in with a different user the game crashes. (Maybe not all was reset properly)

And if I sign out the user from the system, even if I'm sign out from the game, the game crashes,

Thanks,
Jorge

**Comment by MSFT-Heba** [comment]
Hi @JorgeRamonPuig 
The requirement is to:
• Automatically sign the user in to Xbox Live, or offer the user the option to sign in, before gameplay begins.
• Display the user's Xbox gamertag as their primary display and profile name.

For Sign Out, what is recommended is for the game to to use SignInManager's OnPlayerSignOut to handle the player getting out of the game (if a save needs to happen, stats need to be updated, level needs to end, etc).

SignOut() in PlayerAuthentication is recommended for situations where you have multiple players signed in so you can sign out say Player 2, 3 and 4.

One player has to be signed in at all times so Sign Out shouldn't be used on Player 1 or it should at least make sure another player is signed in when it does so.

Hope that helps :)

**Comment by JorgeRamonPuig** [comment]
Finally my uwp game is out now and your plugin works perfect.

Thanks to everyone and will close this issue.
