### ISSUE TITLE
Failed to fix references for method System.Void Leaderboard::UpdateData(System.UInt32) Ver 1804 Release

### ISSUE THREAD

**Issue by Arcanebits** [Microsoft/xbox-live-unity-plugin#235]
The game run without the plugin on visual studio, then add it to the project,, compile the UWP solution
and try to run into the PC not even the xbox one and it fails, here is the main line of error and my conf
Unity 2018.1
SDK: 10.0.16299.0
Visual Studio Comunity 15.6.7
.Net Version 4.7.02556
Script RuntimeVersion .NET 3.5

1>  Running AssemblyConverter...
1>  Failed to fix references for method System.Void Leaderboard::UpdateData(System.UInt32)
1>  Failed to fix references for type Leaderboard
1>  System.Exception: Failed to resolve Microsoft.Xbox.Services.Statistics.Manager.IStatsManager
1>     en Unity.ModuleContext.Retarget(TypeReference type, GenericContext context)
1>     en Unity.ModuleContext.Retarget(MethodReference method, GenericContext context)
1>     en Unity.FixReferencesStep.Visit(MethodDefinition method, GenericContext context)
1>     en Unity.FixReferencesStep.Visit(TypeDefinition type)
1>     en Unity.TypeDefinitionDispatcher.DispatchType(TypeDefinition type)
1>     en Unity.TypeDefinitionDispatcher..ctor(ModuleDefinition module, ITypeDefinitionVisitor visitor)
1>     en Unity.FixReferencesStep.ProcessModule()
1>     en Unity.ModuleStep.Execute()
1>     en Unity.FixReferencesStep.Execute()
1>     en Unity.Step.Execute(OperationContext operationContext, IStepContext previousStepContext)
1>     en Unity.Operation.Execute()
1>     en Unity.Program.Main(String[] args)

Please any help will be more than welcome!
Arcanebits

**Comment by Arcanebits** [comment]
UPDATE
Solved this part, just upgrade the RUNTIMEVERSION from NET 3.5 to 4.X into Unity and Done.
Arcanebits

**Comment by XboxLiveForum** [comment]
Hello, Arcanebits.

Thanks for the update.
We will be closing this thread then.

Thanks!
