### ISSUE TITLE
Player authentication hangs

### ISSUE THREAD

**Issue by Arcanebits** [Microsoft/xbox-live-unity-plugin#237]
I managed to overcome the first issue, but this happens when the game enters the scene where I Drag n Droped  PlayerAuthentication Prefab. Just droped in, did I had to add anything else for the most basic setup? 
Also added the <uap:SupportedUsers>multiple</uap:SupportedUsers> to the Package.appxmanifest file (note the long extention name, is that ok?)

Cheers, 
Arcanebits

![2018-05-04_22-05-47](https://user-images.githubusercontent.com/34106553/39659147-febe1bee-4fef-11e8-9a18-85253202b9b8.jpg)

**Comment by XboxLiveForum** [comment]
Hello, Arcanebits.

Could you please provide the following information?
Once we have these details, we might have a better idea of which direction to take this investigation.

			Required General Information
				• What platform is the issue happening on (XDK, or UWP)?
				• What XSAPI project flavor are they using (C++, WinRT)?
				• What XSAPI version are they using (1612, 1703, etc)?
				• What OS or XDK are they using? (XDK 1703, TH2, etc)
				• Reproduction steps for the issue, if not already obtained
			 
			Additional Helpful Information
				• What error code was encountered?
				• Perhaps a fiddler trace where possible?

**Comment by Arcanebits** [comment]
Hi, and thanks for writing, this are the answers:
1	Platfform: UWP
2	No XSAPI installed just the plugin, im based full on UWP (Do I need XSAPI anyway?_
3	Sdk 16299
The project runs normally without the Xbox Live plugin, I installed it and face the current problem.
Here conf captuires
![vsconf](https://user-images.githubusercontent.com/34106553/39664301-33b3e8ce-504f-11e8-8406-a06990646592.jpg)
![unityconf](https://user-images.githubusercontent.com/34106553/39664302-33cef16e-504f-11e8-8813-813ce9861dbd.jpg)

**Comment by Arcanebits** [comment]
Ok lets close this thread also.
I moved to D3D from XAML since XAML seems to have something quite tied to the UW Error I Had. Also observing the documentation no image ever showed XAML being selected, just D3D, it was my mistake not to pay enough attention to details.
Cheers People!
Arcanebits
