### ISSUE TITLE
Save System Issue

### ISSUE THREAD

**Issue by johnrlisenby** [Microsoft/xbox-live-unity-plugin#239]
Hello,

I'm having an issue with initialization the save system after one session of gameplay. Let me explain.

I’m using Unity 2017.4.3 with the Xbox Plug-in 1804, and when I first boot up the computer I can load sign-in and initialize the save system. I play the game a few minutes and exit the game via a button (application.quit). A few minutes to a few hours later,  I try to reopen the game.  I can sign-in, but I cannot initialize the save system see the picture of the error. If I restart the computer it all works, but error again after I close and reopen the game.

So my question is. Is there anything that keeps the player logged into Xbox Live Services or whatever services that would be cleared on a reboot? Or is there a correct way to sign-out of services when I close my game? The issue seems to only happen on PC. I'm using the Windows 10 0318 version.

As you can see from the picture below, I’m signed into Xbox Live (GT Kavlar 360), but I'm getting the error.
![savesystem error](https://user-images.githubusercontent.com/24777531/40205153-7fba3cee-5a1a-11e8-82b2-9f4d593883fc.PNG)
Thanks,

John

**Comment by johnrlisenby** [comment]
I created an Unity package of the error. I could be doing it wrong. I followed the example from https://github.com/rkhadder/XboxLiveConnectedStorageSample and made some adjustments. I trying to convert the strings back to ints.

My Package download link: https://1drv.ms/u/s!AvZmImUmXkwvhK5_J4YAt_6wNZE7hA

Directions. Download the plugin and extract game saves. Import my package and open the scene. There are 2 scripts and 1 scene file. My setting in Unity: Using 2017.4.3f1 Windows SDK 10.0.17134.0, Scripting version Net 3.5, backend Il2CPP and API Comp level Net 4.6.

Thanks,

John

**Comment by XboxLiveForum** [comment]
Hi John,
Sorry for the delayed response, and thank you for the info you've provided so far.

For this issue, a Fiddler trace might be particularly useful. Could you obtain one of those as well (in .saz format)? Here are instructions if you don't know how:
[https://docs.microsoft.com/en-us/windows/uwp/xbox-live/using-xbox-live/troubleshooting/how-to-set-up-fiddler-for-debugging](url)

You can send it to v-naw@microsoft.com. Once we have that, we'll send this to the next line of support.

Thank you.

**Comment by XboxLiveForum** [comment]
Hi John,
Were you able to get the Fiddler Trace. Please let us know.

-Brett

**Comment by XboxLiveForum** [comment]
Hi @johnrlisenby 
Are you still encountering this issue? If so, could you please obtain a Fiddler capture (.saz file) as requested? One other thing as well: Is this a Creators program project?

Once we have that we can move this to the next line of support. Thanks!

**Comment by johnrlisenby** [comment]
Sorry for the late reply, I was able to get it working with by using Ramsey's example from his GitHub.

**Comment by XboxLiveForum** [comment]
Thanks for letting us know, and glad you were able to get it to work. We will close this thread now.
