### ISSUE TITLE
Failed AOT cross compiler

### ISSUE THREAD

**Issue by xbeto** [Microsoft/xbox-live-unity-plugin#241]
Hello,

I have downloaded the latest version of the plugin (1804) for Unity and I'm getting a "Failed AOT cross compiler" error.

Settings:
==================================================================
Unity Version: 5.6.6f2
Scripting Backend: Mono2x
API Compatibility Level: .Net 2.0 Subset
Script Compiler: Mono

Error 1
==================================================================
Cross compilation job Microsoft.Xbox.Services.UnityEditor.CSharp.dll failed.
UnityEngine.UnityException: Failed AOT cross compiler: C:\Program Files\Unity566f2\Editor\Data\PlaybackEngines\XboxOnePlayer/Tools\mono-xcompiler.exe --aot=full,asmonly,nodebug,print-skipped,outfile="Microsoft.Xbox.Services.UnityEditor.CSharp.dll.s" "Microsoft.Xbox.Services.UnityEditor.CSharp.dll"  current dir : C:\Users\TYR\source\repos\XboxLiveTest\Temp/StagingArea/Data/Managed
 result file exists: False. Timed out: False

stdout:
Mono Ahead of Time compiler - compiling assembly C:\Users\TYR\source\repos\XboxLiveTest\Temp\StagingArea\Data\Managed\Microsoft.Xbox.Services.UnityEditor.CSharp.dll
* Assertion at ..\mono\mono\mini\aot-compiler.c:2326, condition `method->flags & METHOD_ATTRIBUTE_STATIC' not met

stderr:

  at UnityEditor.MonoProcessUtility.RunMonoProcess (System.Diagnostics.Process process, System.String name, System.String resultingFile) [0x000e2] in C:\buildslave\unity\build\Editor\Mono\BuildPipeline\MonoAssemblyStripping.cs:112 
  at UnityEditor.MonoCrossCompile.CrossCompileAOT (BuildTarget target, System.String crossCompilerAbsolutePath, System.String assembliesAbsoluteDirectory, CrossCompileOptions crossCompileOptions, System.String input, System.String output, System.String additionalOptions) [0x0034e] in C:\buildslave\unity\build\Editor\Mono\BuildPipeline\MonoCrossCompile.cs:318 
  at UnityEditor.MonoCrossCompile+JobCompileAOT.ThreadPoolCallback (System.Object threadContext) [0x0002c] in C:\buildslave\unity\build\Editor\Mono\BuildPipeline\MonoCrossCompile.cs:52 
UnityEditor.HostView:OnGUI()

Error 2
===================================================================

UnityException: Cross compilation failed.
UnityEditor.PostProcessXboxOnePlayer.CompileAOTCode (BuildTarget target, BuildOptions options, System.String installPath, System.String stagingAreaData, System.String stagingAreaDataManaged, System.String[]& managedDlls) (at C:/buildslave/unity/build/PlatformDependent/XboxOne/Editor/Managed/PostProcessXboxOnePlayer.cs:191)
UnityEditor.PostProcessXboxOnePlayer.PostProcess (BuildTarget target, BuildOptions options, System.String installPath, System.String stagingAreaData, System.String stagingArea, System.String playerPackage, System.String stagingAreaDataManaged) (at C:/buildslave/unity/build/PlatformDependent/XboxOne/Editor/Managed/PostProcessXboxOnePlayer.cs:451)
UnityEditor.XboxOne.XboxOneBuildPostprocessor.PostProcess (BuildPostProcessArgs args) (at C:/buildslave/unity/build/PlatformDependent/XboxOne/Editor/Managed/ExtensionModule.cs:82)
UnityEditor.PostprocessBuildPlayer.Postprocess (BuildTargetGroup targetGroup, BuildTarget target, System.String installPath, System.String companyName, System.String productName, Int32 width, Int32 height, System.String downloadWebplayerUrl, System.String manualDownloadWebplayerUrl, BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.BuildReporting.BuildReport report) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/PostprocessBuildPlayer.cs:186)
UnityEditor.HostView:OnGUI()

If I switch to IL2CPP, I get a different error(s): 
==================================================================

Error 1
==================================================================
Failed running C:\Program Files\Unity566f2\Editor\Data\Tools/UnusedByteCodeStripper2/UnusedBytecodeStripper2.exe --api NET_2_0_Subset -out "C:\Users\TYR\source\repos\XboxLiveTest\Temp\StagingArea\Data\Managed\tempStrip" -l none -c link -b true -x "C:\Program Files\Unity566f2\Editor\Data\PlaybackEngines\XboxOnePlayer\Whitelists\Core.xml" -f "C:\Program Files\Unity566f2\Editor\Data\il2cpp\LinkerDescriptors" -x "C:\Users\TYR\source\repos\XboxLiveTest\Temp\StagingArea\Data\Managed\..\platform_native_link.xml" -x "C:\Users\TYR\source\repos\XboxLiveTest\Temp\StagingArea\Data/methods_pointedto_by_uievents.xml" -x "C:\Users\TYR\source\repos\XboxLiveTest\Temp\StagingArea\Data\preserved_derived_types.xml" -x "C:\Program Files\Unity566f2\Editor\Data\PlaybackEngines\XboxOnePlayer\Whitelists\AI.xml" -x "C:\Program Files\Unity566f2\Editor\Data\PlaybackEngines\XboxOnePlayer\Whitelists\Animation.xml" -x "C:\Program Files\Unity566f2\Editor\Data\PlaybackEngines\XboxOnePlayer\Whitelists\Audio.xml" -x "C:\Program Files\Unity566f2\Editor\Data\PlaybackEngines\XboxOnePlayer\Whitelists\Cloth.xml" -x "C:\Program Files\Unity566f2\Editor\Data\PlaybackEngines\XboxOnePlayer\Whitelists\Core.xml" -x "C:\Program Files\Unity566f2\Editor\Data\PlaybackEngines\XboxOnePlayer\Whitelists\CrashReporting.xml" -x "C:\Program Files\Unity566f2\Editor\Data\PlaybackEngines\XboxOnePlayer\Whitelists\IMGUI.xml" -x "C:\Program Files\Unity566f2\Editor\Data\PlaybackEngines\XboxOnePlayer\Whitelists\Input.xml" -x "C:\Program Files\Unity566f2\Editor\Data\PlaybackEngines\XboxOnePlayer\Whitelists\JSONSerialize.xml" -x "C:\Program Files\Unity566f2\Editor\Data\PlaybackEngines\XboxOnePlayer\Whitelists\ParticlesLegacy.xml" -x "C:\Program Files\Unity566f2\Editor\Data\PlaybackEngines\XboxOnePlayer\Whitelists\ParticleSystem.xml" -x "C:\Program Files\Unity566f2\Editor\Data\PlaybackEngines\XboxOnePlayer\Whitelists\PerformanceReporting.xml" -x "C:\Program Files\Unity566f2\Editor\Data\PlaybackEngines\XboxOnePlayer\Whitelists\Physics.xml" -x "C:\Program Files\Unity566f2\Editor\Data\PlaybackEngines\XboxOnePlayer\Whitelists\Physics2D.xml" -x "C:\Program Files\Unity566f2\Editor\Data\PlaybackEngines\XboxOnePlayer\Whitelists\Terrain.xml" -x "C:\Program Files\Unity566f2\Editor\Data\PlaybackEngines\XboxOnePlayer\Whitelists\TerrainPhysics.xml" -x "C:\Program Files\Unity566f2\Editor\Data\PlaybackEngines\XboxOnePlayer\Whitelists\TextRendering.xml" -x "C:\Program Files\Unity566f2\Editor\Data\PlaybackEngines\XboxOnePlayer\Whitelists\UI.xml" -x "C:\Program Files\Unity566f2\Editor\Data\PlaybackEngines\XboxOnePlayer\Whitelists\UNET.xml" -x "C:\Program Files\Unity566f2\Editor\Data\PlaybackEngines\XboxOnePlayer\Whitelists\UnityAds.xml" -x "C:\Program Files\Unity566f2\Editor\Data\PlaybackEngines\XboxOnePlayer\Whitelists\UnityAnalytics.xml" -x "C:\Program Files\Unity566f2\Editor\Data\PlaybackEngines\XboxOnePlayer\Whitelists\UnityConnect.xml" -x "C:\Program Files\Unity566f2\Editor\Data\PlaybackEngines\XboxOnePlayer\Whitelists\UnityWebRequest.xml" -x "C:\Program Files\Unity566f2\Editor\Data\PlaybackEngines\XboxOnePlayer\Whitelists\UnityWebRequestAudio.xml" -x "C:\Program Files\Unity566f2\Editor\Data\PlaybackEngines\XboxOnePlayer\Whitelists\Vehicles.xml" -x "C:\Program Files\Unity566f2\Editor\Data\PlaybackEngines\XboxOnePlayer\Whitelists\Video.xml" -x "C:\Program Files\Unity566f2\Editor\Data\PlaybackEngines\XboxOnePlayer\Whitelists\VR.xml" -x "C:\Program Files\Unity566f2\Editor\Data\PlaybackEngines\XboxOnePlayer\Whitelists\Web.xml" -d "C:\Users\TYR\source\repos\XboxLiveTest\Temp\StagingArea\Data\Managed" -a  "C:\Users\TYR\source\repos\XboxLiveTest\Temp\StagingArea\Data\Managed\Assembly-CSharp.dll"

stdout:
Fatal error in Mono CIL Linker
System.NullReferenceException: Object reference not set to an instance of an object.
   at Mono.Linker.Utilities.<GetMethods>c__Iterator1.MoveNext()
   at Mono.Linker.Steps.TypeMapStep.TryMatchMethod(TypeReference type, MethodDefinition method)
   at Mono.Linker.Steps.TypeMapStep.<GetBaseMethodsInInterfaceHierarchy>c__Iterator0.MoveNext()
   at Mono.Linker.Steps.TypeMapStep.MapVirtualInterfaceMethod(MethodDefinition method)
   at Mono.Linker.Steps.TypeMapStep.MapVirtualMethods(TypeDefinition type)
   at Mono.Linker.Steps.TypeMapStep.MapType(TypeDefinition type)
   at Mono.Linker.Steps.TypeMapStep.ProcessAssembly(AssemblyDefinition assembly)
   at Mono.Linker.Steps.BaseStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at Mono.Linker.Driver.RunDriver(Driver driver, IEqualityComparer`1 typeComparer, IEqualityComparer`1 methodComparer)
stderr:

UnityEngine.Debug:LogError(Object)
UnityEditorInternal.Runner:RunManagedProgram(String, String, String, CompilerOutputParserBase, Action`1) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/BuildUtils.cs:96)
UnityEditorInternal.AssemblyStripper:RunAssemblyLinker(IEnumerable`1, String&, String&, String, String) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/AssemblyStripper.cs:102)
UnityEditorInternal.AssemblyStripper:StripAssembliesTo(String[], String[], String, String, String&, String&, String, IIl2CppPlatformProvider, IEnumerable`1) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/AssemblyStripper.cs:95)
UnityEditorInternal.AssemblyStripper:RunAssemblyStripper(String, IEnumerable, String, String[], String[], String, IIl2CppPlatformProvider, RuntimeClassRegistry) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/AssemblyStripper.cs:201)
UnityEditorInternal.AssemblyStripper:StripAssemblies(String, IIl2CppPlatformProvider, RuntimeClassRegistry) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/AssemblyStripper.cs:126)
UnityEditorInternal.IL2CPPBuilder:Run() (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs:143)
UnityEditorInternal.IL2CPPUtils:RunIl2Cpp(String, String, IIl2CppPlatformProvider, Action`1, RuntimeClassRegistry, Boolean) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs:34)
UnityEditor.HostView:OnGUI()

Error 2
==================================================================
Exception: C:\Program Files\Unity566f2\Editor\Data\Tools/UnusedByteCodeStripper2/UnusedBytecodeStripper2.exe did not run properly!
UnityEditorInternal.Runner.RunManagedProgram (System.String exe, System.String args, System.String workingDirectory, UnityEditor.Scripting.Compilers.CompilerOutputParserBase parser, System.Action`1 setupStartInfo) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/BuildUtils.cs:98)
UnityEditorInternal.AssemblyStripper.RunAssemblyLinker (IEnumerable`1 args, System.String& out, System.String& err, System.String linkerPath, System.String workingDirectory) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/AssemblyStripper.cs:102)
UnityEditorInternal.AssemblyStripper.StripAssembliesTo (System.String[] assemblies, System.String[] searchDirs, System.String outputFolder, System.String workingDirectory, System.String& output, System.String& error, System.String linkerPath, IIl2CppPlatformProvider platformProvider, IEnumerable`1 additionalBlacklist) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/AssemblyStripper.cs:95)
UnityEditorInternal.AssemblyStripper.RunAssemblyStripper (System.String stagingAreaData, IEnumerable assemblies, System.String managedAssemblyFolderPath, System.String[] assembliesToStrip, System.String[] searchDirs, System.String monoLinkerPath, IIl2CppPlatformProvider platformProvider, UnityEditor.RuntimeClassRegistry rcr) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/AssemblyStripper.cs:201)
UnityEditorInternal.AssemblyStripper.StripAssemblies (System.String stagingAreaData, IIl2CppPlatformProvider platformProvider, UnityEditor.RuntimeClassRegistry rcr) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/AssemblyStripper.cs:126)
UnityEditorInternal.IL2CPPBuilder.Run () (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs:143)
UnityEditorInternal.IL2CPPUtils.RunIl2Cpp (System.String tempFolder, System.String stagingAreaData, IIl2CppPlatformProvider platformProvider, System.Action`1 modifyOutputBeforeCompile, UnityEditor.RuntimeClassRegistry runtimeClassRegistry, Boolean debugBuild) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs:34)
UnityEditor.PostProcessXboxOnePlayer.CompileAOTCodeIl2Cpp (BuildTarget target, BuildOptions options, System.String installPath, System.String stagingAreaData, System.String stagingAreaDataManaged, System.String playerPackage, System.String[]& managedDlls) (at C:/buildslave/unity/build/PlatformDependent/XboxOne/Editor/Managed/PostProcessXboxOnePlayer.cs:269)
UnityEditor.PostProcessXboxOnePlayer.PostProcess (BuildTarget target, BuildOptions options, System.String installPath, System.String stagingAreaData, System.String stagingArea, System.String playerPackage, System.String stagingAreaDataManaged) (at C:/buildslave/unity/build/PlatformDependent/XboxOne/Editor/Managed/PostProcessXboxOnePlayer.cs:444)
UnityEditor.XboxOne.XboxOneBuildPostprocessor.PostProcess (BuildPostProcessArgs args) (at C:/buildslave/unity/build/PlatformDependent/XboxOne/Editor/Managed/ExtensionModule.cs:82)
UnityEditor.PostprocessBuildPlayer.Postprocess (BuildTargetGroup targetGroup, BuildTarget target, System.String installPath, System.String companyName, System.String productName, Int32 width, Int32 height, System.String downloadWebplayerUrl, System.String manualDownloadWebplayerUrl, BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.BuildReporting.BuildReport report) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/PostprocessBuildPlayer.cs:186)
UnityEditor.HostView:OnGUI()

Thanks for the help.

Regards.

**Comment by XboxLiveForum** [comment]
Hi @xbeto <p>

Can you provide the following information?
<ol>
<li> Is this a Creators program request?
<li> What IDE and version are you using?
<li> What version of the Windows SDK are you using?
<li> Repro steps for this issue?
</ol>
Once we have this information, we will submit a request to get this looked at. <p>
Thanks!

**Comment by XboxLiveForum** [comment]
Hi @xrjguajardo <p>
Thanks for the info. I think there might be a bit of confusion here. Are you actually an <a href="https://www.xbox.com/en-US/developers/id">ID@Xbox</a> developer? I believe that only ID@Xbox has access to the XDK and dev kits, and the page you linked above references materials for ID@Xbox or managed partners. <p>The <a href="https://docs.microsoft.com/en-us/windows/uwp/xbox-live/developer-program-overview">Creators program</a> uses a subset of the overall Xbox Live service features. For ID@Xbox developers, the Xbox Live Unity Plugin does not yet support all the features you will need. Instead, read the document <a href="https://docs.microsoft.com/en-us/windows/uwp/xbox-live/get-started-with-partner/get-started-with-xbox-live-partner">Get Started with Xbox Live for ID and Managed Partners</a> for guidance.

**Comment by XboxLiveForum** [comment]
Hi @xrjguajardo <p>
Was the information in the last post useful? If you still need assistance, please let us know, we will be glad to assist you. <p>
Best regards

**Comment by xrjguajardo** [comment]
Hi, yes, we are going through the documentation, we have received support from someone at ID@Xbox Dev support, and we got setup on XDP and now we are supposed to be able to work on the service config. I'm going to look on it today. thanks for your help and clarification.

**Comment by MSFT-Heba** [comment]
Hopefully this issue is resolved now :) Closing this issue. Please feel free to reopen the issue or create a new one is needed
