### ISSUE TITLE
Sign in

### ISSUE THREAD

**Issue by max-pasichnyk** [Microsoft/xbox-live-unity-plugin#247]
Hello,
I'm developing a game for Windows 10 (UWP) with Unity 2017 and trying to integrate the xbox live plugin. Unity editor works fine, but build crash when I use SignInSilentlyAsync.
When I'm use SignInAsync I got error 0x80860003
![image](https://user-images.githubusercontent.com/11374170/43305675-52e3ff2c-9181-11e8-95ed-ee75b9ff2f6d.png)

**Comment by kamathaj** [comment]
How did you solve this issue?

**Comment by cjSEG6** [comment]
Hi, did you find a solution to this issue? Can’t find any answers surrounding this
