### ISSUE TITLE
"Imported Type 'System.threading.tasks.task' is defined multiple times.

### ISSUE THREAD

**Issue by snair692** [Microsoft/xbox-live-unity-plugin#250]
So I've been trying to get this to work for like 8 hours. I am on the latest version of Unity, the latest version of visual studio 2017, and the latest version of this plugin.

I have tried targeting both .NET 4.X  IL2CPP backend and .NET 3.5 with the .NET backend. I followed the instructions on enabling/disabling the DLL's appropriately within the editor. 

I am at a loss, if I disable the Unity.Tasks dll the visual studio IDE errors go away, but the unity errors will not go away and I cannot compile. 

Assets/Xbox Live/Scripts/UnityTaskExtensions.cs(23,79): error CS0433: The imported type `System.Threading.Tasks.Task<TResult>' is defined multiple times

If I target .NET 3.5 with .NET backend and don't remove unitytasks.dll from the project then these errors continue, if I remove it then these errors go away but instead I get a new error:  

Assets/Xbox Live/Scripts/SignInManager.cs(579,93): error CS0012: The type `System.Threading.Tasks.Task`1<Microsoft.Xbox.Services.SignInResult>' is defined in an assembly that is not referenced. Consider adding a reference to assembly `Unity.Tasks, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'

I've seen other people reporting this bug or similar bugs to it since the end of 2017. Wondering what exactly is causing this and how I can get this to work right now?

**Comment by snair692** [comment]
I was actually able to get this figured out, it was something else in Unity that had also imported the System.Threading.Tasks dll, I removed it, which broke that unity addon, but fixed this issue.

**Comment by Abuelitovip** [comment]
why you don´t use the asset XboxLive.unitypackage?
[http://github.com/Microsoft/xbox-live-unity-plugin/releases/latest](http://github.com/Microsoft/xbox-live-unity-plugin/releases/latest)

**Comment by MSFT-Heba** [comment]
Looks like this issue has already been resolved. Closing this issue, but please feel free to reopen or create a new issue as needed.

**Comment by JorgeRamonPuig** [comment]
Hello, I've the same issue with the last version of the pluggin.

But I don't have the System.threading.dll in my project and I don't know how yo remove It.

Any idea?

**Comment by naaturaz** [comment]
Same over here. Once I load the XboxLive Package I get:
Assets\Xbox Live\Scripts\UnityTaskExtensions.cs(62,16): error CS0433: The type 'Task' exists in both 'Unity.Tasks, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' and 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'

I have tried many different things. Any help is appreciated. I'm rusty on Visual Studio

Thanks a lot

**Comment by ChaosRift** [comment]
Same issue on Unity 2018.3.12f1. .net 4.x, il2cpp ... . Deleted Unity.tasks... 

Assets\Xbox Live\Scripts\SignInManager.cs(599,69): error CS0012: The type 'Task<>' is defined in an assembly that is not referenced. You must add a reference to assembly 'Unity.Tasks, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.

Assets\Xbox Live\Scripts\SignInManager.cs(616,65): error CS0012: The type 'Task<>' is defined in an assembly that is not referenced. You must add a reference to assembly 'Unity.Tasks, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
