### ISSUE TITLE
 “Test” button on developer centre returns "Publish failed"

### ISSUE THREAD

**Issue by prosthetichead** [Microsoft/xbox-live-unity-plugin#254]
I'm fast running out of ideas and I can not work out how to fix this. I am unable to setup my sandbox on the developer console for xbox live. When I press the Test button all that is returned is "Publish failed" nothing explaining why or how it failed, I'm unable to test using my sandbox and I have no idea or help with how to fix it.

I'm hoping someone here might know why or what to do to fix this issue, please help. let me know if there is any additional information that you might need to help me fix this.

**Comment by MSFT-Heba** [comment]
Hi @prosthetichead 
Can you check if you're still seeing this issue?
If you are, could you please see if you can get a fiddler trace? If you haven't tried Fiddler before, this tutorial could help: [https://www.telerik.com/videos/fiddler/getting-started-with-fiddler-web-debugging-proxy ](https://www.telerik.com/videos/fiddler/getting-started-with-fiddler-web-debugging-proxy )

**Comment by prosthetichead** [comment]
It works now Thank You!

**Comment by MSFT-Heba** [comment]
Sounds great! Closing this issue now :) Please feel free to reopen or create a new one as needed!
