### ISSUE TITLE
Update all documentation

### ISSUE THREAD

**Issue by magius96** [microsoft/xbox-live-unity-plugin#276]
The documentation is horribly behind on this project.  Especially the page that supposed to detail the Unity Prefabs.  Can someone please update the documentation for this project?

**Comment by MSFT-Heba** [comment]
Hey there,
Just for awareness, we've posted an announcement that integrating Xbox Live is **no longer a requirement for UWP games to be published on Xbox as part of the Creators Program** and we are phasing out software needed to support Xbox Live on UWP. 

For more details: https://github.com/microsoft/xbox-live-unity-plugin#2021-update-more-accessible-creators-program-no-longer-requires-xbox-live
