### ISSUE TITLE
Home readme link to documentations gives 404

### ISSUE THREAD

**Issue by GabLeRoux** [microsoft/xbox-live-unity-plugin#278]
> See the docs at https://docs.microsoft.com/en-us/windows/uwp/xbox-live/get-started-with-creators/develop-creators-title-with-unity

In the meantime, here's a link to a cached version of the page from google:  
https://webcache.googleusercontent.com/search?q=cache:TtDGBU59iREJ:https://docs.microsoft.com/en-us/gaming/xbox-live/get-started-with-creators/develop-creators-unity+&cd=1&hl=en&ct=clnk&gl=ca

But most links you'll click on that page also bring to some 404 :(

**Comment by rook909** [comment]
Thanks for the cached version.  I was looking for this but to no avail!

**Comment by Murtaya** [comment]
Looks like the cached page is now unavailable, too :(

**Comment by Murtaya** [comment]
Is this the same document?
https://docs.microsoft.com/en-us/gaming/xbox-live/get-started/setup-ide/creators/unity-win10/configure-xbox-live-in-unity

**Comment by jasonsandlin** [comment]
Yes, that's the right

**Comment by MSFT-Heba** [comment]
Hey everyone,
Just a quick update. We've posted an announcement that integrating Xbox Live is no longer a requirement for UWP games to be published on Xbox as part of the Creators Program and we are phasing out software needed to support Xbox Live on UWP. 

For more details: https://github.com/microsoft/xbox-live-unity-plugin#2021-update-more-accessible-creators-program-no-longer-requires-xbox-live
