### ISSUE TITLE
Is this repo unsupported and/or dead?

### ISSUE THREAD

**Issue by stonstad** [microsoft/xbox-live-unity-plugin#283]
Zero activity.  No support.  No updates.  

Is this repository officially unsupported?

e.g. I submitted this issue in March (https://github.com/microsoft/xbox-live-unity-plugin/issues/274) and there was no response.  All or most issues created in the last year remain unanswered.

**Comment by stonstad** [comment]
@jasonsandlin

**Comment by jasonsandlin** [comment]
Yes, we still monitor this project to ensure there aren't any blocking issues that prevent folks from shipping Xbox Live Creators games.  If we missed anything blocking, please let us know.  For issues that are annoying, they are on our radar and we hope to get to them when we can but at this time we aren't announcing any significant updates to this plugin.

**Comment by stonstad** [comment]
Thanks, Jason!

**Comment by phime** [comment]
Hey @jasonsandlin this is annoying :) Title-managed Stats & Leaderboards are not working
#288
