### ISSUE TITLE
Published title on the store won't authenticate/sign-in

### ISSUE THREAD

**Issue by pistolpig** [microsoft/xbox-live-unity-plugin#292]
Firstly, apologies if this doesn't belong here. Tell me if I need to go to MSDN forums or something instead.

I've recently published a game to the store.

The game signed into XBL with fake data within Unity with no problems. It also signed in with real data on Windows 10 when built appropriately from VS. Finally, it also signed into XBL properly on the XBox in the sandbox. 

Published the game to the store and now the sign-in is ignoring input.

Frustrating as heck, because without a user signed in, my game won't proceed to the leader board, and if it doesn't proceed to the leader board, it just leaves the player hanging.

Anyone else have this problem? Something obvious I need to change between the local version and the version on the store?

**Comment by MSFT-Heba** [comment]
Hey there,
Sorry for the delay.

Just an FYI. We've posted an announcement that integrating Xbox Live is no longer a requirement for UWP games to be published on Xbox as part of the Creators Program and we are phasing out software needed to support Xbox Live on UWP. 

For more details: https://github.com/microsoft/xbox-live-unity-plugin#2021-update-more-accessible-creators-program-no-longer-requires-xbox-live
