### ISSUE TITLE
Incompatibility with new Unity Input System?

### ISSUE THREAD

**Issue by Snigros** [microsoft/xbox-live-unity-plugin#295]
To duplicate:

1.  Create a new project with Unity 2019.3.2f1.
2.  Add 1.1.0-Preview 5 package, restart editor (leave both input systems enabled in player).
3.  Add Xbox Live Plugin package from: https://github.com/Microsoft/xbox-live-unity-plugin/releases/tag/v1804qfe3
4.  Xbox package imports but console displays error:

Library\PackageCache\com.unity.inputsystem@1.0.0-preview.5\InputSystem\Editor\EditorInputControlLayoutCache.cs(38,35): error CS0433: The type 'Tuple<T1, T2>' exists in both 'Unity.Compat, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' and 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'

I don't understand this error so any assistance with resolving would be greatly appreciated.

Thanks, Snig.

**Comment by Snigros** [comment]
Apologies for raising...have resolved by following suggestion for disabling plugins from https://github.com/microsoft/xbox-live-unity-plugin/issues/293, and also settings for Unity Editor NET46 DLLs...plus multiple restarts of Unity...

**Comment by LJ-Court** [comment]
Just for anyone else with this issue or one similar if you are using .net 4.x then follow the same steps but disable Unity Editor NET35 DLLs
