### ISSUE TITLE
Multiple Errors in Unity 2019.3.5f1

### ISSUE THREAD

**Issue by LJ-Court** [microsoft/xbox-live-unity-plugin#297]
When using this i get these errors:

"Library\PackageCache\com.unity.burst@1.3.0-preview.5\Runtime\Intrinsics\x86\Csr.cs(213,10): error CS0433: The type 'MonoPInvokeCallbackAttribute' exists in both 'Microsoft.Xbox.Services.UnityEditor.CSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' and 'UnityEngine.CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'"

"Library\PackageCache\com.unity.burst@1.3.0-preview.5\Runtime\Intrinsics\x86\Csr.cs(206,10): error CS0433: The type 'MonoPInvokeCallbackAttribute' exists in both 'Microsoft.Xbox.Services.UnityEditor.CSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' and 'UnityEngine.CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'"

"Library\PackageCache\com.unity.burst@1.3.0-preview.5\Runtime\BurstRuntime.cs(142,14): error CS0433: The type 'MonoPInvokeCallbackAttribute' exists in both 'Microsoft.Xbox.Services.UnityEditor.CSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' and 'UnityEngine.CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'"

Does anyone have any idea how to solve these

**Comment by smooth2795** [comment]
Did you solve this?

**Comment by LJ-Court** [comment]
Yeah I think I did honestly can't remember now
