### ISSUE TITLE
Unable to import plugin in Unity 2019-3-10f1

### ISSUE THREAD

**Issue by cookiedot** [microsoft/xbox-live-unity-plugin#301]
Hello,
my game runs with Unity 2019-3-10f1 and i try today to import the xbox live package... and get errors.
I've do all the required things (check 4.6/uncheck 3.5 Dll)..
the errors are: "Assets\Xbox Live\Scripts\UnityTaskExtensions.cs(93,20): error CS0433: The type 'Task' exists in both 'Unity.Tasks, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' and 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'"
What can i do? 1 year of hard work on my game and i can't add requested sign in of Xbox live to publish it... :'(
Help...

**Comment by cookiedot** [comment]
If it can help someone, i've make that and all the errors are gone....:
in NET35 directory of the Xbox live plugin, i've unchecked "Auto reference" and "validate reference" in addition to "editor".
Except for Unity.compat, i've only unchecked "editor" and checked "Auto reference" and "validate reference".
in NET46 directory of the Xbox live plugin, i've checked these in addition to "editor".
Save (important) with ctrl+S, Unity work and all errors are gone...

**Comment by ChossyUK** [comment]
Can you please go into more detail i have gone from 1 error to over 150 trying to follow your instructions

**Comment by cookiedot** [comment]
Hello,
here's my three steps to avoid the errors:

**First in Xbox live plugin, directory Libs/UnityEditor/NET35, i unchek all for three files (show picture)**
![step1](https://user-images.githubusercontent.com/65357005/82018084-cc8f1500-9684-11ea-90e0-bfcfd87185c0.jpg)
**Second, same directory, i check Auto Reference and validate references for Unity.Compat**
![step2](https://user-images.githubusercontent.com/65357005/82018085-cdc04200-9684-11ea-9232-855eef95d857.jpg)
**Third, in directory Libs/UnityEditor/NET46, i check only Auto Reference,validate references and editor:**
![step3](https://user-images.githubusercontent.com/65357005/82018087-cdc04200-9684-11ea-8992-1b6874aea482.jpg)

Save, and all errors are gone for me.
I use Unity 2019-3-10f1, Visual Studio 2019, Windows 10 SDK (latest). Warning, if you have TextMeshpro package in your unity project and you don't use it, remove it. It has some incompatibility with XBox live Plugin. And i use the QF2 version of the Xbox Plugin, the latest QF3 seems to have some problems.

Hope it helps.

**Comment by cookiedot** [comment]
And i've forgotten, you must fill the configuration for association with your app on partner center. Xbox Live Association doesn't work for me so i've open the conf manually and fill all the fields...
