### ISSUE TITLE
Missing namespaces.

### ISSUE THREAD

**Issue by Stanlyhalo** [microsoft/xbox-live-unity-plugin#313]
I downloaded version 1803, and imported it into unity 2020.1.2f1. However I get a ton of errors such as:
`Assets\Xbox Live\Scripts\SignInManager.cs(19,34): error CS0246: The type or namespace name 'Singleton<>' could not be found (are you missing a using directive or an assembly reference?)`
and
`Assets\Xbox Live\Scripts\PlayerAuthentication.cs(26,16): error CS0246: The type or namespace name 'Theme' could not be found (are you missing a using directive or an assembly reference?)`

And these errors occur after I enabled the NET46 libs in the editor and disabled the NET35 libs even though my api compatability is set to 4.x.

I also don't get a menu button saying "Xbox Live" like I'm suppose too, I also tried the latest version of the release packages, and it still doesn't work.

**Comment by MSFT-Heba** [comment]
Hey there,
Hey there,
Sorry for the delay. Unfortunately Unity 2020 is not supported.

That being said, we've posted an announcement that integrating Xbox Live is no longer a requirement for UWP games to be published on Xbox as part of the Creators Program and we are phasing out software needed to support Xbox Live on UWP. For more details: https://github.com/microsoft/xbox-live-unity-plugin#2021-update-more-accessible-creators-program-no-longer-requires-xbox-live
