### ISSUE TITLE
Store Listing

### ISSUE THREAD

**Issue by PhoenixDev92** [microsoft/xbox-live-unity-plugin#314]
Hi, 

I know this isn't directly related to the plugin, but has anyone been able to find how to access Creators Collection games from the redesigned Xbox Store? If they've permanently removed it then it would be almost impossible for players to find our games without searching for them.

**Comment by dhood55** [comment]
I actually have the same question. Doesn't look like there's any visibility right now. I do have apps on the store already, before the redesign and after, and I'm still getting a decent amount of downloads, so I'm kinda stumped on whether there's visibility in certain areas or not.

**Comment by PhoenixDev92** [comment]
That's what I was wondering, I can see that my page views have dropped to 0 but I'm still getting downloads as well. The problem is that I released a new game and that one has got almost no attention at all since there is no way for people to find it. I've tried reaching out to Partner Center support but they said to try and contact Xbox Support but I have been unsuccessful so far

**Comment by dhood55** [comment]
> That's what I was wondering, I can see that my page views have dropped to 0 but I'm still getting downloads as well. The problem is that I released a new game and that one has got almost no attention at all since there is no way for people to find it. I've tried reaching out to Partner Center support but they said to try and contact Xbox Support but I have been unsuccessful so far

Yeah, that right there is what has been my worry for future products, and for the future of xbox indie devs. And I'd say the same as well, practically 0 page views, but I'm getting downloads. Although, from what I've been reading, the creators collection games seem to now be compatible with the Xbox Series X/S (and seems that my games are compatible with the new generation as well), which wouldn't make too much sense if they were to remove the creators collection. 

My assumption is that it will eventually be back on the store, but I feel like we won't see it for a while, considering the store is still in early stages. I don't think it will pop back up in the next few months, which sucks for devs that release a game during this time, like so. Hope I'm right that it'll be back and wrong on the length of time it comes back.

**Comment by Murtaya** [comment]
Yes, I've logged bugs and complained to the Microsoft Store team about it.  I'm not sure if they even understand that Creator's Collection is a completely stand-alone set of games (the dev I talked to in the bug seemed to think it was just another collection like Recent Releases or Most Popular, and as such, users could access the games from other areas...which they can't).  So, I wouldn't expect much from them at the moment.

I did talk to some people on the dev support side, and they didn't seem to be aware that Creators Collection wasn't available in the new store app.  They said they'd flag it as needing to be addressed as they supposedly still plan to support the Creators Program on all Xbox hardware.

Disclaimer: I work for Microsoft, but not in any of these areas; I make video games for a hobby for both ID@Xbox and Creators Program and am just as upset about the state of this plugin and the Creators Collection as anybody.

**Comment by MSFT-Heba** [comment]
Hey there,
Unfortunately this is outside of the scope of this plugin but we have raised this with the right team.

Just for awareness, we've posted an announcement that integrating Xbox Live is no longer a requirement for UWP games to be published on Xbox as part of the Creators Program and we are phasing out software needed to support Xbox Live on UWP. For more details: https://github.com/microsoft/xbox-live-unity-plugin#2021-update-more-accessible-creators-program-no-longer-requires-xbox-live
