### ISSUE TITLE
Achievements 

### ISSUE THREAD

**Issue by LenaAGM** [microsoft/xbox-live-unity-plugin#316]
Is it possible to add achievements to Unity(c#) game if we have already joined The ID @ Xbox Program?

**Comment by Murtaya** [comment]
Yes, but you need to use a different plugin, if I'm remembering correctly:
https://docs.microsoft.com/en-us/gaming/xbox-live/get-started/setup-partner-center/legacy/live-get-started-xbl-partner

**Comment by LenaAGM** [comment]
I have already done leaderboards and data saving using this plugin https://docs.microsoft.com/en-us/gaming/xbox-live/get-started/setup-ide/creators/unity-win10/live-configure-xbl-in-unity. 

and then I needed to make achievements and had to use another plugin according to this instruction https://docs.microsoft.com/en-us/gaming/xbox-live/get-started/setup-ide/managed-partners/unity-win10/live-partner-unity-uwp-il2cpp. but because of the use of the first plugin, there was a conflict because of the same namespaces. how to solve this? maybe you could send me this api unity package with a different namespace?

01 ноября 2020, 08:02:57, от Murtaya <notifications@github.com>:



Yes, but you need to use a different plugin, if I'm remembering correctly:
https://docs.microsoft.com/en-us/gaming/xbox-live/get-started/setup-partner-center/legacy/live-get-started-xbl-partner
