### ISSUE TITLE
Roadmap for this plugin/Creator's Program?  Possible to use this for 2018+ Unity, or wait for the new GDK?

### ISSUE THREAD

**Issue by Murtaya** [microsoft/xbox-live-unity-plugin#317]
I'm trying to port a game to Xbox/Creator's Collection.  The game was built in Unity 2020.1.1, and much like a lot of other people in these issue threads, I'm seeing all sorts of issues (even when I try with a completely blank project).  I was able to at least get the Xbox Live tab to appear using info [from this thread](https://github.com/microsoft/xbox-live-unity-plugin/issues/306), but I'm still unable to build because of the issue with duplicate Task (which unfortunately wasn't solved by the suggestions in [this thread](https://github.com/microsoft/xbox-live-unity-plugin/issues/284)).  I've tried versions from 1802 through 1804 with no luck.

It sounds like this plug in is just [no longer expected to work](https://github.com/microsoft/xbox-live-unity-plugin/issues/296) for any versions of Unity past 2017 (2018, 2019, 2020, etc.).  Is this true/expected?  The last project I was able to port was a 2017, and even that was a pain.

Additionally, it really looks like Microsoft is phasing out UWP games and the Creator's Collection with the way this plug in is being abandoned, with the new console Store not exposing any Creator's Collection games, UWP games not being supported by certain future platforms, etc.  

**Is there any advice on what indie developers can do to get their games on the console via self-serve?**  For example:
- **Should they just stay on Unity 5.6.4/2017/etc. version and version 1802 of this plugin?**
- **Should they wait for the new GDK?**  Is the new GDK even expected to be available publicly, or will it be locked down to 1st/3rd parties and ID@Xbox?
- **Is a new version of this plugin in the works that will fix the issues with the more recent Unity builds?**
- **Are they just out of luck for the foreseeable future** (i.e., Microsoft isn't planning on continuing self-serve game publishing)?

I know it's a busy season for Microsoft with the new consoles shipping, but any help and suggestions (and especially any future roadmaps) would be much appreciated.  I'm really hoping Microsoft continues to be inclusive to indie devs and support the diversity they bring to gaming.

Thanks-
Mike

**Comment by jasonsandlin** [comment]
The current plugin only supports Unity 5.5 to Unity 2017.  We are working towards removing the requirement to use this plugin for Creators submissions but there’s no official change yet to announce. Stay tuned

**Comment by Snigros** [comment]
HI,

Any updates from Microsoft on where they are going with this?

P.S. It is possible to use this plugin with later versions of Unity.  I used VS 2019 and Unity 2020.2.1f1 for my free game (Arachnophobic Kyle -  now available on the Microsoft Store) - however it was a very painful process that literally wasted months of my time getting it to work...

**Comment by Murtaya** [comment]
I haven't heard anything more than what Jason said.  Personally, even if we remove the requirement to use it for CC, that means that we'd lose per-user data storage, which I don't want to do.  I think I'm just gonna wait for the GDK and hope it becomes available.

Thanks for the info on getting it to work with the newer versions of VS and Unity--I spent about 30% of my game's implementation time just trying to get the plug in working (well, kinda) with the supported versions--I can imagine how hard it was to get it working with the unsupported versions.

**Comment by jasonsandlin** [comment]
Sorry for the delay.  The Store policy has been updated at https://docs.microsoft.com/en-us/windows/uwp/publish/store-policies which now states:

> Dec 16, 2020 Policy Update Notice: For game products targeting console developed through the Xbox Live Creators program, the requirement to integrate with XBL Services no longer applies. The specific policy (Policy 10.13.1) will be updated to reflect this change the next time the Store Policy document is updated, but effective as of this notice, the policy will no longer be enforced for the XBL Creators Program.

@Murtaya, you should be able to use the stock UWP storage solutions.  See https://docs.microsoft.com/en-us/windows/uwp/design/app-settings/store-and-retrieve-app-data

**Comment by Snigros** [comment]
Jason,

Thanks for the update re removing the requirement for integration with XBL Services.  As an aside, is there an "official" site we can refer to for information about what the new GDK will provide (and when it will be available)?

Thanks, S

**Comment by jasonsandlin** [comment]
There's nothing public to announce at this time.

**Comment by sstrong2** [comment]
See [https://docs.microsoft.com/en-us/windows/uwp/publish/store-policies-change-history](url)

**Comment by TigerCollins** [comment]
@jason

> There's nothing public to announce at this time.

It's been well over a year, is there anything to report at this time. My project has multiplayer functionality and ID@xbox is a nightmare to get into without the GDK/plugin unless I'm with a large studio or have a publisher backing

**Comment by jasonsandlin** [comment]
The public GDK was actually recently announced. You can learn about the public GDK here: https://github.com/microsoft/GDK

**Comment by TigerCollins** [comment]
Amazing! Thank you?  I'm a little confused about its implementation with Unity, do I not need ID@Xbox approval prior?

**Comment by jasonsandlin** [comment]
You should ask any GDK related questions on https://github.com/microsoft/GDK.  That team can best answer and perhaps can make their docs more clear for anything that's not yet clear.  Thanks

**Comment by MSFT-Heba** [comment]
Hey everyone,
We've posted an announcement that integrating Xbox Live is no longer a requirement for UWP games to be published on Xbox as part of the Creators Program and we are phasing out software needed to support Xbox Live on UWP. For more details: https://github.com/microsoft/xbox-live-unity-plugin#2021-update-more-accessible-creators-program-no-longer-requires-xbox-live
