### ISSUE TITLE
Error when signing in test player on Xbox One

### ISSUE THREAD

**Issue by singularity-gs** [microsoft/xbox-live-unity-plugin#319]
I've been able to successfully deploy my Unity (2019.4.12) game to my Xbox One.  However, when trying to actually sign in a test user during the game, I get the rather cryptic error message: 

XboxException: Xbox Services flat C API return error code -1000 with message "Provider Error: Unexpected response code: Unknown error: 0x80131509"

I've researched this quite a bit and have yet to find a solution.  I've accounted for what seem to be the typical gotchas...
- I added and validated two test user accounts on my Xbox...this issue happens with both
- I added <uap:SupportedUsers>multiple</uap:SupportedUsers> to the <Properties> section of my Package.appxmanifest file
- I switched my Xbox to Developer mode and to the appropriate sandbox ID (and added that Sandbox ID to the console in the Partner center website)
- In Visual Studio, I did the project->right click->Store->Associate... function.  That did solve another error, but not this one
- My XboxServicdes.config file has all the right values from my Partner Center page
- I even followed all the instructions in the Test section of the Services/Xbox Live page on Partner Center

I'd love to at least get more information as to what the specific error is.  I apologize if this isn't the correct forum for this issue.  If there's a better place to post, please feel free to direct me there.  Thank you!

**Comment by jasonsandlin** [comment]
This github repo only covers the Creators Unity plugin for UWP, and not the GDK version.  For ID@XBox support, post the question on the ID@Xbox forums.
