### ISSUE TITLE
unity 

### ISSUE THREAD

**Issue by fgsoftware1** [microsoft/xbox-live-unity-plugin#320]
follow attach of errors

![hexagon - MainMenu - Universal Windows Platform - Unity 2019 4 19f1 Personal _DX11_ 02_02_2021 18_29_43](https://user-images.githubusercontent.com/60277618/106645763-b4e61c80-6584-11eb-8102-fb9eaf2b7be4.png)

**Comment by TigerCollins** [comment]
Have you found a solution to this? 

The solution I found that's not ideal is having to remove all of the burst and newtonsoft packages from the Unity Package Manager. A lot of packages have them as dependencies is the downside.

**Comment by fgsoftware1** [comment]
> Have you found a solution to this?
> 
> The solution I found that's not ideal is having to remove all of the burst and newtonsoft packages from the Unity Package Manager. A lot of packages have them as dependencies is the downside.

no

**Comment by MSFT-Heba** [comment]
Hey everyone,
Just a quick update. We've posted an announcement that integrating _Xbox Live is no longer a requirement for UWP games to be published on Xbox as part of the Creators Program_ and we are phasing out software needed to support Xbox Live on UWP. For more details: https://github.com/microsoft/xbox-live-unity-plugin#2021-update-more-accessible-creators-program-no-longer-requires-xbox-live
