### ISSUE TITLE
Not showing on Unity 2020.1.3f1

### ISSUE THREAD

**Issue by TuxPenguin09** [microsoft/xbox-live-unity-plugin#322]
I imported the package, and just 4 errors, and "Xbox Live" isn't showing up in the Menu bar as they said.

**Comment by TigerCollins** [comment]
I made a post about this issue on the [Unity forums](https://forum.unity.com/threads/xbox-live-plugin-clashing-with-package-manager-assets.1080701/). Xbox Live will show up when there are no errors and it can compile properly - Simple solution, fix the errors.

 However, I don't know what your error is, but I can imagine it's "multiple precompiled assemblies with the same name" (newtonsoft.dll) or multiple 'MonoPInvokeCallbackAttribute.cs' scripts. If it's not one of them, please do share. 

A fix is to remove every package related to Newtonsoft and Burst from the Unity Package Manager but then you won't easily be able to use packages such as animation rigging, dots or auto multithreaded physics. I know it sucks, it's halted my current project.

**Comment by MSFT-Heba** [comment]
Hey there,
Sorry for the delay. Unfortunately Unity 2020 is not supported.

We've posted an announcement that integrating Xbox Live is no longer a requirement for UWP games to be published on Xbox as part of the Creators Program and we are phasing out software needed to support Xbox Live on UWP. For more details: https://github.com/microsoft/xbox-live-unity-plugin#2021-update-more-accessible-creators-program-no-longer-requires-xbox-live
