### ISSUE TITLE
Seems Abandoned

### ISSUE THREAD

**Issue by PatrickB3** [microsoft/xbox-live-unity-plugin#323]
There hasn't been an update for over a year. The latest version doesn't work and never did.
The Association Wizard doesn't work in any version.
Editing the XboxServices.config by hand sucks.
No version works with Unity 2021. Conflicts with like everything.
The plugin also accesses the internet wrong causing timing issues. It doesn't wait for a response so it the response isn't instant it crashes. Unity fixed one of them (for cloud saves) in their forums but Microsoft never integrated the fix, or fixed the others. https://forum.unity.com/threads/solved-uwp-xbox-live-creators-cloud-save-connected-storage-issue.655441/

I would just avoid it. Xbox Live is isn't required any more. You lose the Leaderboards which sucks but they were always kinda iffy anyways.

Unrelated to the plugin. The Store Association never gets the right certificate from the store. So if by some miracle you get this plugin to actually work. You have to remember in Visual Studio to go to the Packaging tab in the package.appxmanifest. Choose Certificate, Select from Store, and choose one that isn't expired and dated on or after the date you created the project on the partner web site or else it won't run after signing in.

Good luck with your games!

**Comment by Snigros** [comment]
PatrickB3 - totally agree with your summary.  In its current form the code is a complete mess and makes the process of getting something up on the Xbox so much harder than it probably should be (for independent developers).   There does seem to be some hint that something better might be coming (see hints of a new GDK in discussion under issue #317) - but I am not holding my breath given how poorly supported the current plugin has been.  Very disappointing performance from Microsoft.

**Comment by MSFT-Heba** [comment]
Hi everyone,
Sorry for the delay.

We've posted an announcement that integrating Xbox Live is no longer a requirement for UWP games to be published on Xbox as part of the Creators Program and we are phasing out software needed to support Xbox Live on UWP. For more details: https://github.com/microsoft/xbox-live-unity-plugin#2021-update-more-accessible-creators-program-no-longer-requires-xbox-live
