### ISSUE TITLE
Xbox config dialog pops up after doing a build

### ISSUE THREAD

**Issue by payzer** [Microsoft/xbox-live-unity-plugin#47]
Every time I do a build, the Xbox configuration dialog window pops up. Do you know if that is on purpose?

I'm on Unity 5.5 in case that helps.

**Comment by veleek** [comment]
Nope, that should not happen.  It's likely due to the way that Unity deals with UI windows.  Accessing the class causes the window to open.  We can probably fix this by moving the logic the the post processing steps use out of the UI window and into a shared class that both pieces use.

**Comment by jasonsandlin** [comment]
Closing this and will track this internally
