### ISSUE TITLE
Name vs. ID for stats

### ISSUE THREAD

**Issue by payzer** [Microsoft/xbox-live-unity-plugin#64]
This is minor, but it was a bit confusing that Stats have a property called "ID", but in the Unity prefab it's called "Name" (I figured they were the same, but had to double check the code to make sure). Would it be possible to have the names be consistent?

**Comment by jasonsandlin** [comment]
Thanks.  We will look into this

**Comment by jasonsandlin** [comment]
Closing this and will track this internally
