### ISSUE TITLE
 Throw new Exception ("Sign in Failed"); is an exception that can not be caught and the game may stop.

### ISSUE THREAD

**Issue by nanmo** [Microsoft/xbox-live-unity-plugin#65]
Hi, everyone,

I am seeing commitment (0d0af23).
I am going to develop Xbox Live, but I've been worried about looking at the source code.
That is, in the SignInAsync method of UserProfile.cs, processing to raise the following exception is done.

https://github.com/Microsoft/xbox-live-unity-plugin/blob/master/Assets/Xbox%20Live/Scripts/UserProfile.cs
(Line 101-105)
``` 
        // Throw any exceptions if needed.
        if (signInTask.Result.Status != SignInStatus.Success)
        {
            throw new Exception("Sign in Failed");
        }
```
Probably an exception is thrown when the sign-in fails for any reason.

Because I can not catch this exception, I am worried that the application (game) will stop and the error message will continue to be displayed to the user.

If you have problems like the above, please fix it.
Do you have any plans to change this sign-in process?

For example, in order to deal with this issue, XboxLive.cs which forked XboxLive.cs of the previous commit (e23e0a9) is published by "nakfiv".
https://github.com/nakfiv/XboxLiveConnect/blob/master/Assets/Xbox%20Live/Scripts/XboxLive.cs
(Line 84-89)

**Comment by jasonsandlin** [comment]
Thanks for the report.  We will look into this and get back to you

**Comment by nanmo** [comment]
I have confirmed that throwing the exception is almost being replaced by a new debug/log mechanism.
I think it's a wonderful changes.

I think that changes will be reflected in the next release, so I will close this issue as soon as I can confirm the next "Official Release".
Is that okay?

**Comment by jasonsandlin** [comment]
Yes, thanks

**Comment by jasonsandlin** [comment]
This should be solved in our 1707 release.  Thanks!

**Comment by nanmo** [comment]
Thanks a lot!
