### ISSUE TITLE
Leaderboard Scene not working correctly when entering a second time

### ISSUE THREAD

**Issue by KloppeMedia** [Microsoft/xbox-live-unity-plugin#97]
Leaderboard Scene works fine when entered the first time, but when loading another scene and then going back to Leaderboard Scene, Player Stats are not shown and not possible to flush new Stats.

**Comment by MSFT-Heba** [comment]
Hi KloppeMedia,
Are you using the latest release? There was a similar bug that was fixed in it that could possibly be what you're encountering.

**Comment by KloppeMedia** [comment]
I am using v1707, i guess this should be the latest version.

**Comment by MSFT-Heba** [comment]
That should be the latest yes: https://github.com/Microsoft/xbox-live-unity-plugin/releases/tag/v1707

I tried to repro on my side by starting with the leaderboard scene and adding a button to load a new scene. The new scene only has a button that takes you back to the leaderboard scene. And unfortunately couldn't repro. Leaderboard loaded every time I went back.

Going to need your help a bit to get to the bottom of this. Is my setup above similar to what you have? Do you have anything else in there?

**Comment by KloppeMedia** [comment]
Sorry, maybe i was a bit unclear, the leaderboard is loaded fine, including its entries.
But the PlayerStat (StatsPanel) does not show the value and you can not flush stats.

This is the leaderboard scene i am using:
[http://km-games.com/wp-content/uploads/2017/07/xboxlivelb.png](url)

**Comment by MSFT-Heba** [comment]
Hi KloppeMedia,
That was indeed a bug. A fix was just merged into the code. 
Could you please see if the fix works for you as well?

What you'll need to do is download the repo and build the package locally. [Instructions for Unity Plugin Setup and Build](https://github.com/Microsoft/xbox-live-unity-plugin/blob/master/README.md)

**Comment by KloppeMedia** [comment]
Great, it work now, thanks!

**Comment by DutyStudios** [comment]
I'm having a problem with this still. I have already downloaded the latest and replaced most of the files. This is the error I am getting.

MissingReferenceException: The object of type 'RectTransform' has been destroyed but you are still trying to access it.
Your script should either check if it is null or you should not destroy the object.
Leaderboard.LoadResult (Microsoft.Xbox.Services.Leaderboard.LeaderboardResult result) (at Assets/Xbox Live/Scripts/Leaderboard.cs:275)
Leaderboard.GetLeaderboardCompleted (System.Object sender, XboxLivePrefab.StatEventArgs e) (at Assets/Xbox Live/Scripts/Leaderboard.cs:246)
StatsManagerComponent.OnGetLeaderboardCompleted (XboxLivePrefab.StatEventArgs statEvent) (at Assets/Xbox Live/Scripts/Stats/StatsManagerComponent.cs:92)
StatsManagerComponent.Update () (at Assets/Xbox Live/Scripts/Stats/StatsManagerComponent.cs:60)
